DFE-Digital/get-help-to-retrain

- Gemfile.lock
- package.json
- yarn.lock
Getting latest changes from Boilerplate which this Repo is forked from
> Get latest changes from Boilerplate

- Gemfile
- Gemfile.lock
- app/models/category.rb
- app/models/job_profile.rb
- app/models/skill.rb
- app/services/seed_service.rb
- db/seeds.rb
- spec/factories/categories.rb
- spec/factories/job_profiles.rb
- spec/factories/skills.rb
- spec/models/category_spec.rb
- spec/models/job_profile_spec.rb
- spec/models/skill_spec.rb
- spec/rails_helper.rb
- spec/support/factory_bot.rb
I'll be using these factories shortly for setting up some test data fixtures, but I think this is already useful as a standalone PR.
This adds some factory bot factories for the key models using Faker to populate attributes. Also added some very simplistic tests to debug the has many relationships - all working nicely now.
> Add some factories and specs for models

- README.md
This is just a simple PR to point the build badge to the DfE account.
> Update build badge to the dfe-ssp account

- app/controllers/job_profiles_controller.rb
- app/models/category.rb
- app/models/job_profile.rb
- app/views/job_profiles/index.html.erb
- app/views/job_profiles/search.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_contact_us.html.erb
- app/webpacker/images/search_icon.svg
- app/webpacker/styles/_contact-us.scss
- app/webpacker/styles/_job-profile.scss
- app/webpacker/styles/application.scss
- config/locales/en.yml
- config/routes.rb
- spec/.rubocop.yml
- spec/features/view_pages_spec.rb
- spec/models/category_spec.rb
- spec/models/job_profile_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-56
* Build Job Profile responsive search and results page 
* Search is case insensitive
* Add base for beta banner and breadcrumbs
> GET-56 Build Job Profile Search page and Results page

- Dockerfile
We'd like the container to be self-starting with a simple docker run
Adding the `CMD` entry to the Dockerfile
> Executable container

- azure-pipelines.yml
- azure/template.json
Update the build name after the gitsha and expose that as a parameter on the pipeline
> GET-63 Update variable and build name git sha

- app/controllers/categories_controller.rb
- app/controllers/check_your_skills_controller.rb
- app/controllers/explore_occupations_controller.rb
- app/helpers/application_helper.rb
- app/helpers/explore_occupations_helper.rb
- app/helpers/job_profile_helper.rb
- app/models/category.rb
- app/views/categories/show.html.erb
- app/views/check_your_skills/index.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/explore_occupations/index.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/home/index.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/search/_results_form.html.erb
- app/views/shared/search/_results_list.html.erb
- app/webpacker/styles/_contact-us.scss
- app/webpacker/styles/_job-profile.scss
- azure-pipelines.yml
- config/locales/en.yml
- config/routes.rb
- features/56-Careers-Search.feature
- features/62-Job-Categories.feature
- spec/factories/categories.rb
- spec/helpers/application_helper_spec.rb
- spec/helpers/explore_occupations_helper_spec.rb
- spec/models/category_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-62
* add css linter to pipeline
* move check your existing skills out of Job Profile controller into its own controller/views
* add explore occupations controller/views with categories list
* tidy up views and add partials for shared forms
> GET-62 Add Explore Occupations page with category list

- app/views/categories/show.html.erb
- app/views/check_your_skills/index.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/explore_occupations/index.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/home/index.html.erb
- app/views/home/task_list.html.erb
- app/views/shared/navigation/_main_header.html.erb
- app/webpacker/styles/_task-list.scss
- app/webpacker/styles/application.scss
- config/locales/en.yml
- config/routes.rb
- features/35-Landing-Page.feature
- features/56-Careers-Search.feature
jira-ticket: https://dfedigital.atlassian.net/browse/GET-30
* Add static task list page
* Add task-list css styles
* add task list breadcrumb to all views
> GET-30 Add Task list page

- .rubocop.yml
- spec/.rubocop.yml
> Add rubocop styles

- azure/template.json
In order for the app to access the database we need to define some firewall rules.
Allow webapp outbound IPs to access the database
> Postgres firewall rules

- Dockerfile
- startup.sh
> Initialise the DB

- app/views/job_profiles/show.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-161
> GET-161 Change copy on job profile button

- app/views/home/find_training_courses.html.erb
- app/views/home/task_list.html.erb
- app/views/job_profiles/show.html.erb
- config/locales/en.yml
- config/routes.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-60
* add course page and link to it from task list page
* add breadcrumbs for page
> GET-60 Add find training course page

- app/decorators/job_profile_decorator.rb
- spec/decorators/job_profile_decorator_spec.rb
Remove all links from job profile sections. E.g /job_profiles/auditor
https://dfedigital.atlassian.net/browse/GET-146
> Remove all links from all job profile sections

- app/views/job_profiles/_highlights.html.erb
- app/views/job_profiles/show.html.erb
- app/webpacker/styles/_job-profile.scss
jira-ticket: https://dfedigital.atlassian.net/browse/GET-143
* Allow highlights section to span full page and maintain call block to
be the last section
* add margins for sections for now until design finalised in next sprint
> GET-143 Fix job profile page stylings

- azure/template.json
https://dfedigital.atlassian.net/browse/GET-154
Enable app-service-logs on the web app  service.
This PR is just to enable the log collection on the web app service.
> GET-154 Enable application logs.

- app/models/job_profile.rb
- app/scrapers/job_profile_scraper.rb
- app/views/job_profiles/_related_profiles.html.erb
- app/views/job_profiles/show.html.erb
- app/views/skills/index.html.erb
- app/webpacker/styles/_job-profile.scss
- db/migrate/20190701095914_create_related_job_profiles.rb
- db/schema.rb
- spec/models/job_profile_spec.rb
- spec/scrapers/job_profile_scraper_spec.rb
As a user
I want to see occupations related to mine
So that I am made aware about other potential occupations
```ruby
irb(main):002:0> JobProfile.second.related_job_profiles
JobProfile Load (0.7ms)  SELECT  "job_profiles".* FROM "job_profiles" ORDER BY "job_profiles"."id" ASC LIMIT $1 OFFSET $2  [["LIMIT", 1], ["OFFSET", 1]]
JobProfile Load (0.6ms)  SELECT  "job_profiles".* FROM "job_profiles" INNER JOIN "related_job_profiles" ON "job_profiles"."id" = "related_job_profiles"."related_job_profile_id" WHERE "related_job_profiles"."job_profile_id" = $1 LIMIT $2  [["job_profile_id", 1816], ["LIMIT", 11]]
=> #<ActiveRecord::Associations::CollectionProxy []>
irb(main):003:0> JobProfile.second.related_job_profiles << JobProfile.all[5]
JobProfile Load (0.7ms)  SELECT  "job_profiles".* FROM …
```
> Display related careers on skills/job profile pages

- app/views/pages/find_training_courses.html.erb
- app/views/shared/_what_you_can_do_next.html.erb
- config/locales/en.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-185
This should link to the next steps page
> GET-185 Add What you can do next section on courses hub page

- app/views/pages/task_list.html.erb
- app/webpacker/styles/_task-list.scss
- config/locales/en.yml
Update the contact number for advisers.
Pages it needs to be present on:
Hub (tasklist)
Check your existing skills + results
Existing skills overview
Job title search + results / job category search + results
Job profile information
Next steps
https://dfedigital.atlassian.net/browse/GET-29
> Update phone number

- app/views/layouts/application.html.erb
Reverts DFE-Digital/get-help-to-retrain#68
> Revert "GET-174 Add google verification to stop indexing"

- app/views/layouts/application.html.erb
- app/views/pages/task_list.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-134
Add extra section on task list page for link to survey. This should
load through the same page. Add link to feedback in banner, this one
should go to a different tab.
> GET-134 Add link to smart survey for feedback

- package.json
- yarn.lock
> Update lodash.merge dependency due to security vulenrability

- app/views/pages/next_steps.html.erb
Add local Liverpool apprenticeship link to next steps page
https://dfedigital.atlassian.net/browse/GET-192
> Add local Liverpool apprenticeship link to next steps page

- yarn.lock
resolves following alerts: https://github.com/DFE-Digital/get-help-to-retrain/network/alerts
> Resolve lodash security alerts

- app/views/pages/find_training_courses.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-213
> GET-213 Change helpline times

- app/views/pages/find_training_courses.html.erb
- app/views/shared/_contact_us.html.erb
- config/locales/en.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-214
Design approved by Ruben
> GET-214 Add time section on call us section

- app/helpers/job_profiles_helper.rb
- app/views/check_your_skills/_results_list.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/skills/index.html.erb
- config/routes.rb
- spec/helpers/job_profiles_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-216
* Dashify all routes
* Change query params to make sure search is preserved to "search" to
avoid long urls
deployed and ready for testing: https://s108d01-dev-as.azurewebsites.net/
> GET-216 Dashify all routes

- Dockerfile
- Gemfile
- azure-pipelines.yml
- Remake the pipeline using Azure Tasks
- Introduce multi-stage to make room to include releases
- Introduces service connections to the Docker HUB registry to avoid managing credentials to use it.
> azure-pipelines.yml overhauling. 

- app/views/home/index.html.erb
- app/views/pages/find_training_courses.html.erb
- app/views/pages/task_list.html.erb
- spec/features/task_list_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-218
> GET-218 Task list content change

- app/views/home/index.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-217
> GET-217 Update content and link on landing page

- app/webpacker/packs/search-form.js
> Capture name change from name to search

- app/models/course.rb
- db/migrate/20190718095913_create_courses.rb
- db/schema.rb
- spec/factories/courses.rb
- spec/models/course_spec.rb
Create the infrastructure to support the courses data.
https://dfedigital.atlassian.net/browse/GET-224
> Create infrastructure for courses

- .gitignore
- azure-pipelines.yml
- azure/config/ci.parameters.json
- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/dev3.parameters.json
- azure/config/test.parameters.json
- azure/template.json
This PR makes use of the new Azure multi-stage pipelines so we can manage deployment from the azure-pipelines.yaml.
https://devblogs.microsoft.com/devops/whats-new-with-azure-pipelines/
This refactoring also changed the way deployment variables are passed when deploying to environments. We moved from inline overriding of params to a per environment config file which is versioned.
This was possible because secrets were moved into Azure KeyVault and they are now just a reference.
ToDo:   While testing this change I could see some value in having a common parameter file that applies to *all* envs, so that things are a bit more DRY
Config files for upper environments will be added on separate PRs after migration takes place.
I appreciate that the first stage is a bit redundant now and it's …
> Pipeline v2

- azure/config/test.parameters.json
Adds the test config and updates the references to the test subscription Keyvault
> Add test env config

- azure-pipelines.yml
Added a condition on the deploy stage, so that it only triggers on master.
> Deploy only on master branch

- app/views/pages/english_overview.html.erb
- app/views/pages/maths_overview.html.erb
- app/views/shared/_contact_us.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/course_overview_pages_spec.rb
Course Type Overview for Maths & English
https://dfedigital.atlassian.net/browse/GET-120
/pages/english_overview
/pages/maths_overview
> Add maths/english overview static pages

- lib/tasks/data_import/import_sitemap.rake
- lib/tasks/data_import/refresh_job_profiles.rake
- lib/tasks/data_import/scrape_categories.rake
- lib/tasks/data_import/scrape_job_profiles.rake
Just fixing an out of date comment (Copy and Paste error)..
> Small documentation fix for rake task

- app/controllers/courses_controller.rb
- app/controllers/pages_controller.rb
- app/helpers/form_helper.rb
- app/models/course.rb
- app/models/course_geospatial_search.rb
- app/views/courses/index.html.erb
- app/views/home/index.html.erb
- app/views/pages/location_eligibility.html.erb
- app/webpacker/packs/search-form.js
- config/brakeman.ignore
- config/features.rb
- config/locales/en.yml
- config/routes.rb
- spec/features/find_training_courses_spec.rb
- spec/features/location_eligibility_spec.rb
- spec/helpers/form_helper_spec.rb
- spec/models/course_geospatial_search_spec.rb
- spec/models/course_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-36
* Add location eligibility behind feature flag
* Refactor Geolocation search for cleanup and validations
* Add Form helper, taken from: https://github.com/DFE-Digital/dfe-teachers-payment-service/blob/master/app/helpers/govuk_form_helper.rb
> GET-36 Check location eligibility 

- app/admin/categories.rb
- app/admin/courses.rb
- app/admin/job_profiles.rb
- app/admin/skills.rb
Some fixes and improvements to admin pages
* Fixed default sort order for all admin pages
* Fixed ability to edit courses (was throwing an error on save)
* Added ability to edit skills (to change name and enabled)
Admin pages are only available in development mode, so will need to pull branch and test locally if required.
> Get 233 admin updates

- azure/config/dev2.parameters.json
> Fix dev2 url

- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/dev3.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
This PR is a review of the configuration for all current environments.
> Review config for all environments

- azure-pipelines.yml
- azure/config/ci.parameters.json
- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/dev3.parameters.json
- azure/config/test.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
https://dfedigital.atlassian.net/browse/GET-290
Adds Azure Alert rules
> Get 290/alerting

- app/views/shared/feedback/_survey.html.erb
Pa11y expects us to define a title attribute on the
iFrame.
> Add a title attribute on the SmartSurvey iFrame

- azure/config/uat.parameters.json
https://beta.nrs-ghtr.org.uk/    -> UAT
> Set beta hostname to UAT

- app/controllers/courses_controller.rb
- app/controllers/pages_controller.rb
- app/views/courses/index.html.erb
- config/environments/production.rb
- spec/features/find_training_courses_spec.rb
- spec/requests/pages_spec.rb
- spec/support/feature_flags.rb
We want to persist the user input postcode on the session so that when I go to find courses I don't get a broken journey.
https://dfedigital.atlassian.net/browse/GET-349
> Persist user input postcode on the session

- app/views/courses/index.html.erb
- app/views/pages/task_list.html.erb
- app/views/shared/_contact_us.html.erb
- config/locales/en.yml
- spec/features/task_list_spec.rb
Copy changes for:
- call advisor section
- next steps section
- courses page section
https://dfedigital.atlassian.net/browse/GET-318
> Update copy changes for call advisor section

- azure-pipelines.yml
> Make sure to update apt-get before installing

- app/views/job_profiles/_highlights.html.erb
- app/views/job_profiles/show.html.erb
- app/views/shared/_boost_job_prospects.html.erb
- config/locales/en.yml
A few design tweaks requested by Steve.
https://get-help-to-retrain-prototype.herokuapp.com/main/release2_e2e_v3/job_details_retraining_admin_assistant#main-content
> A few design tweaks for Job Profiles

- app/views/skills_matcher/_no_results.html.erb
- app/views/skills_matcher/index.html.erb
- spec/features/skills_matcher_spec.rb
- spec/features/task_list_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-364
> GET-364 Return different view if no results present in skill matcher

- spec/models/skills_matcher_spec.rb
- spec/support/capybara.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-407
* Add logging to flakey spec for further debugging when it fails
* Always reset session after test in features
> GET-407 Add logging and reset session in features after each spec

- app.json
Setting up Heroku review apps
This will replicate vars from the parent heroku app and also make a backup of the parent postgres DB so we have some useful reference data for testing. I also removed the node buildpack as it's not required and slows down the deployment.
Interesting article on review apps that explains how they work: https://thoughtbot.com/blog/running-acceptance-with-review-apps
> Add required config for heroku review apps

- app/views/home/index.html.erb
- app/views/pages/location_eligibility.html.erb
Adding additional HTML data attributes to support good practice for cypress tests to index and location_eligibility views
Adding three 'data-cy' attributes
> Adding additional HTML data attributes for cypress

- Gemfile
- Gemfile.lock
- README.md
- app.json
- app/models/category.rb
- app/models/course.rb
- app/models/job_profile.rb
- app/models/job_profile_category.rb
- app/models/job_profile_search.rb
- app/models/job_profile_skill.rb
- app/models/primary_active_record_base.rb
- app/models/restricted_active_record_base.rb
- app/models/session.rb
- app/models/skill.rb
- app/models/user_session.rb
- azure-pipelines.yml
- azure/template.json
- config/database.yml
- config/environments/production.rb
- config/initializers/session_store.rb
- db/restricted_migrate/20190904130544_add_sessions_table.rb
- db/restricted_schema.rb
- db/schema.rb
- spec/models/skills_matcher_spec.rb
- spec/models/user_sessions_spec.rb
- spec/rails_helper.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-445
* Enable database switching in config
* Add restricted database with migrations path
* Add truncation to new db in tests
* Specify connection in models to which db to connect to
* Point restricted database credentials to primary db for now, this is until we pick our stategy for multiple db connections in azure
* Use active record session store gem to setup new table for sessions in restricted db
* Add config and specifically point to class as the different db connection is not automatically read
* Add new database setup to heroku review apps and azure
* Add new key to user_session to preserve order of job profile ids, as that is lost when written to db as hashmap
> GET-445 Add new Restricted database, and change session store

- app/services/notify_service.rb
> Add new confirmation id

- azure/config/ut.parameters.json
Those keys have been added to the Key vault in azure as well
> Add missing keys to UT environment

- app/controllers/users_controller.rb
- app/views/users/registration_email_sent_again.html.erb
- app/views/users/registration_results_saved.html.erb
- app/views/users/sign_in_email_sent_again.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/user_registration_spec.rb
- spec/features/user_sign_in_spec.rb
- spec/routing/users_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-494
Add new path and page for resend link on user sign in
> GET-494 Return to results resend email

- config/locales/en.yml
Update title and paragraph copy on check your skills page.
https://dfedigital.atlassian.net/browse/GET-487
> Title and paragraph changes

- config/locales/en.yml
Updated contact us partial to align with prototype changes.
> Updated copy for contact us partial

- app/controllers/job_profiles_controller.rb
- app/controllers/skills_controller.rb
- app/models/skills_builder.rb
- app/models/user_session.rb
- app/views/job_profiles/skills/index.html.erb
- app/views/skills/v2/_job_profiles_with_skills.html.erb
- app/views/skills/v2/index.html.erb
- app/webpacker/styles/_skills-builder.scss
- config/routes.rb
- spec/features/skills_builder_spec.rb
- spec/features/skills_builder_v2_spec.rb
- spec/models/skills_builder_spec.rb
- spec/models/user_sessions_spec.rb
- spec/routing/job_profiles_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-423
* Fix skills builder bugs and add new content
* Add ability to remove job profile from skills page
> GET-423 Skills Builder v3

- app/views/pages/english_overview.html.erb
- app/views/pages/maths_overview.html.erb
These are links within the same service so shouldn't open in a new window.
> Don't open find course links in a new window

- app/views/courses/index.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-492
Agreed with stakeholders to move paragraph under zero courses (as opposed to prototype)
> GET-492 Zero courses page content changes

- app/decorators/job_profile_decorator.rb
- app/views/skills_matcher/_job_matches.html.erb
- app/webpacker/styles/_job-profile.scss
- config/locales/en.yml
- spec/decorators/job_profile_decorator_spec.rb
- spec/features/skills_matcher_spec.rb
Add accordion component for growth scores
Add explanation for each growth type using the accordion
GDS component.
https://dfedigital.atlassian.net/browse/GET-489
> Add growth score explanations

- azure/template.json
Hotfix for database username mismatch
> hotfix for the username mismatch

- config/locales/en.yml
> Amended wording for partial on training hub page

- app/views/users/show.html.erb
- app/views/users/sign_in_email_sent_again.html.erb
jira-ticket; https://dfedigital.atlassian.net/browse/GET-525
> GET-525 Content changes for link/link sent again

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/services/health_check/environment_check.rb
- app/services/health_check/host_name_check.rb
- app/services/health_check/report_service.rb
- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/dev3.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
- config/application.rb
- config/initializers/sentry.rb
- spec/services/health_check/environment_check_spec.rb
- spec/services/health_check/host_name_check_spec.rb
Setup integration with Sentry.io to provide production exception tracking.
This requires new environment variable SENTRY_DSN to be set. If not present then Sentry is not activated. Also includes some additions to health endpoint - this now includes the hostname and environment name (dev / qa / uat etc.), which are also used for context in Sentry.
Ask me for sentry credentials. Relevant SENTRY_DSN has been setup on Heroku already, but also needs to be populated in Azure vault. Also need to think about how each environment will be defined so we can identify them in Sentry UI.
> Sentry.io integration

- app/views/pages/location_eligibility.html.erb
- app/views/pages/location_ineligible.html.erb
- app/views/users/show.html.erb
- app/views/users/sign_in_email_sent_again.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-511
> GET-511 Change breadcrumbs on sign in pages, and fix old wrong ones

- app/views/home/index.html.erb
Service is no longer restricted to these three regions.
> Remove redundant bullet point on start page

- app/views/pages/location_eligibility.html.erb
> Remove example postcode from postcode eligibility page

- app/views/pages/location_ineligible.html.erb
- config/locales/en.yml
Changed heading and replaced text paragraphs to match updated content design.
See location ineligible page.
> Update content for location ineligible page

- app/views/check_your_skills/index.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/courses/index.html.erb
- app/views/home/index.html.erb
- app/views/job_profiles/show.html.erb
- app/views/job_profiles/skills/index.html.erb
- app/views/pages/_next_steps_v1.html.erb
- app/views/pages/_next_steps_v2.html.erb
- app/views/pages/english_overview.html.erb
- app/views/pages/location_eligibility.html.erb
- app/views/pages/location_ineligible.html.erb
- app/views/pages/maths_overview.html.erb
- app/views/pages/task_list.html.erb
- app/views/pages/training_hub.html.erb
- app/views/shared/_save_or_return_to_your_results.html.erb
- app/views/skills/index.html.erb
- app/views/skills/v2/index.html.erb
- app/views/skills_matcher/index.html.erb
- app/views/user_personal_data/index.html.erb
- app/webpacker/styles/_course.scss
- spec/features/user_authentication_sidebar_spec.rb
- spec/features/user_registration_spec.rb
- spec/features/user_sign_in_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-532
* On all pages if user selected skills they should see save your
results partial, otherwise they should see return to save results.
* Maintain logic in hiding partials on registration/sign in
* Fix tests to check all pages instead of certain ones for partials
> GET-532 If user selected skills they should see save your results in sidebar

- app/controllers/courses_controller.rb
- app/views/courses/index.html.erb
- spec/features/find_training_courses_spec.rb
Show 10 results per page on the courses page.
https://dfedigital.atlassian.net/browse/GET-369
> Add pagination to courses page

- app/views/pages/privacy_policy.html.erb
- app/views/user_personal_data/_form.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/your_information_spec.rb
Add privacy policy page. Also, link to it from PID.
https://dfedigital.atlassian.net/browse/GET-462
`/privacy-policy` or from PID form.
> Add privacy policy page

- app/views/check_your_skills/_results_list.html.erb
- app/views/courses/_course.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/cookies_policy.html.erb
- app/views/skills/index.html.erb
- app/views/skills/v2/_job_profiles_with_skills.html.erb
- app/views/skills_matcher/_job_matches.html.erb
- app/webpacker/styles/_job-profile.scss
- app/webpacker/styles/_skills-builder.scss
- config/locales/en.yml
- config/routes.rb
- spec/features/home_spec.rb
Adds new cookies policy page and links to both that and privacy policy page in the footer.
Draft for now - agreeing content first on Heroku review app.
Designs for footer are based on those found in the heroku prototype.
Also found an existing screen reader CSS class while working on this so cleaned up the custom `sr-only` class we recently added.
Content is signed off now :)
> Add cookies policy page

- app/views/job_profiles/_valuable_skills.html.erb
- app/views/job_profiles/skills/index.html.erb
- app/views/pages/task_list_items/_item_1.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/training_hub/_english.html.erb
- app/views/shared/training_hub/_maths.html.erb
- app/views/skills/v2/_job_profiles_with_skills.html.erb
- app/views/user_personal_data/_form.html.erb
- config/initializers/filter_parameter_logging.rb
Adding locators to further elements for cypress to run a fuller journey and capture some accessibility data.
Just a few data-cy attributes on a the PID, task list and the search page.
> Cypress locators for axe accessibility journey in smoke tests

- azure/config/prod.parameters.json
Use the GA ID in the production environment
> Use GA prod ID in production

- app/views/pages/cookies_policy.html.erb
> Tweak wording on cookie policy page

- azure/config/uat.parameters.json
https://dfedigital.atlassian.net/browse/GET-624
Updates the tracking code in config.
> Change UAT's GA tracking code to be disctint from production

- azure-pipelines-deploy-template.yml
> Use windows-2019 agent for deployments

- app/views/home/index.html.erb
- app/views/job_profiles/skills/index.html.erb
- app/views/pages/task_list.html.erb
- app/views/pages/training_hub.html.erb
- app/views/skills/_job_profiles_with_skills.html.erb
- app/views/skills_matcher/index.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-552
* Start page, task list, your skills, job matches increase size of
initial paragraph
* Job skills, training hub reduce 2nd (and 3rd for only traiing hub)
paragraphs
> GET-552 Make styles across pages consistent

- app/services/health_check/check_base.rb
- app/services/health_check/courses_check.rb
- app/services/health_check/environment_check.rb
- app/services/health_check/features_check.rb
- app/services/health_check/find_a_job_check.rb
- app/services/health_check/host_name_check.rb
- app/services/health_check/job_profiles_check.rb
- app/services/health_check/notify_check.rb
- app/services/health_check/postcodes_check.rb
- app/services/health_check/sessions_check.rb
- config/environments/production.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-557
Add staggered caching for health checks, all should be less than a minute
> GET-557 Add caching for health checks

- azure-pipelines-deploy-template.yml
Workaround for https://developercommunity.visualstudio.com/content/problem/784094/no-agent-found-in-pool-azure-pipelines-which-satis.html
Removes indirect dependency on PowerShell by 3rd party Azure Tasks
> Remove PowerShell indirect dependency

- azure-pipelines.yml
https://dfedigital.atlassian.net/browse/GET-581
Adds a stage dependent on QA for the smoke-tests
> GET-581 Add smoke tests to QA

- app/views/skills/_job_profiles_with_skills.html.erb
Both edit/remove links need a description of
which role they are referring to.
https://dfedigital.atlassian.net/browse/GET-583
> Skills builder accessibility fixes

- app/controllers/job_profiles_controller.rb
- app/views/skills/index.html.erb
- app/webpacker/styles/_alerts.scss
- app/webpacker/styles/application.scss
- config/locales/en.yml
- spec/features/skills_builder_spec.rb
We want to inform the users which role they remove
by displaying a flash message.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html
Design info
https://github.com/alphagov/govuk-design-system-backlog/issues/2
https://dfedigital.atlassian.net/browse/GET-658
> Inform user on which roles are removed

- README.md
> Update readme with latest specs

- azure/config/dev2.parameters.json
- azure/config/qa.parameters.json
We had a database outage that Microsoft is investigating.
We need to keep the broken database intact until they run their analysis.  
This PR creates an alternative domain database for the duration of the incident.
> Create a temporary database

- azure-pipelines-deploy-template.yml
- azure/docker-compose-azure.yml
- azure/template.json
https://dfedigital.atlassian.net/browse/GET-667
This PR changes the deployment from a single container WebApp to a multi-container WebApp.
This will allow us to run another container side-by-side with the app using the same config to start asynchronous tasks.
> GET-667 multicontainer application

- app/views/pages/action_plan.html.erb
- app/views/pages/offers_near_me.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/action_plan_spec.rb
- spec/routing/action_plan_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-602
* Add new offers near me route protected by feature flag
* Add offers near me page that is accessible from action plan 
* Didn't add tracking to links as they don't open in new tabs
> GET-602 Add Offers near me page

- azure/config/dev2.parameters.json
Reverts the temporary domain db we used to validate the qa environment
> Revert temp db on dev2

- azure-pipelines.yml
> Explicitly use node version in azure pipeline

- app/views/job_vacancies/index.html.erb
Update content for when:
a) user gets job results
b) user does not get any results
https://dfedigital.atlassian.net/browse/GET-622
> Jobs near me error message

- azure/config/dev1.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/template.json
Use P1V2 ASP in selected environments
Dev1, qa, UAT, PROD
> Use P1V2 ASP in selected environments

- app/views/job_profiles/_relevant_sections.html.erb
prototype: https://get-help-to-retrain-prototype.herokuapp.com/main/release4_e2e_v2/job_details_retraining_admin_assistant
https://get-help-to-retrain-pr-321.herokuapp.com/job-profiles/admin-assistant
> Add title to select type of work section

- app/controllers/application_controller.rb
- app/controllers/job_profiles_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/questions_controller.rb
- app/helpers/question_helper.rb
- app/models/user_session.rb
- app/views/pages/_job_hunting.html.erb
- app/views/pages/_training.html.erb
- app/views/pages/action_plan.html.erb
- app/views/pages/task_list_items/v2/_item_3.html.erb
- app/views/questions/job_hunting.html.erb
- app/views/questions/training.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/action_plan_spec.rb
- spec/features/job_profile_spec.rb
- spec/features/jobs_near_me_spec.rb
- spec/features/questions_spec.rb
- spec/features/task_list_v2_spec.rb
- spec/helpers/question_helper_spec.rb
- spec/models/user_session_spec.rb
- spec/routing/action_plan_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-600
* Add pages for training and job hunting
* If pages answered skip from targeted jobs
* Add different logic for action plan to show what you selected
> GET-600 Add Questions for training and job hunting

- app/views/pages/task_list.html.erb
- config/locales/en.yml
- New h1 paragraph
- New subtitle
https://dfedigital.atlassian.net/browse/GET-641
> Content updates on Task List

- app/services/health_check/sessions_check.rb
- spec/services/health_check/report_service_spec.rb
- spec/services/health_check/sessions_check_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-692
> GET-692 If sessions are zero we now issue a fail instead of a warn

- app/views/skills/index.html.erb
- spec/features/skills_builder_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-660
The title doesn't change (double checked with Lois)
> GET-660 Amend content on skills page when no skills selected

- app/views/home/index.html.erb
https://dfedigital.atlassian.net/browse/GET-640
Just removed `and` from last bullet point!
> Update copy for start page

- azure/template.json
https://dfedigital.atlassian.net/browse/GET-748
This PR updates the deployment API version on the service template, as well as updating the ARM schema version.
It is also making calls against the updated APIs on the generic resource templates [here](https://github.com/DFE-Digital/get-help-to-retrain-devops/commit/d414d835feaac0ceb14e61d18a33024358ae4ffd
)
> Upgrade deployment API version

- app/views/errors/jobs_near_me_error.html.erb
- app/views/skills_matcher/_job_matches.html.erb
- config/locales/en.yml
- spec/features/task_list_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-702
> GET-702 Underline links in job matches

- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_prev_page.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-582
* Add aria lable for next/previous pages
* Add aria label to indicate current page and total pages (taken from
DAC recommendation)
> GET-582 Add aria labels for pagination

- app/views/pages/_job_hunting.html.erb
- app/views/pages/offers_near_me.html.erb
jira-tickets: https://dfedigital.atlassian.net/browse/GET-723
> GET-723 Amend content for outside links

- app/views/shared/_contact_us.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-722
> GET-722 Update advisor text for xmas/new year

- app/views/questions/training.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-721
> GET-721 Add details to training questions, and amend p size

- app/webpacker/styles/_job-profile.scss
* Align salary separtor on certain break points to the left
* Change width to 40% to align with responsive section break
Walked through this with Steve fox (2) and he's happy with it
> Fix salary range

- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/template.json
Clean up code for  Azure Infrastructure  that has become obsolete by recent changes.
- Remove AAI resource
- Remove Azure monitoring Alerts
> Arm cleanup

- lib/tasks/data_import/update_recommended_job_profiles.rake
jira-ticket: https://dfedigital.atlassian.net/browse/GET-845
> GET-845 Remove EU official from recommended jobs

- app/controllers/questions_controller.rb
- app/helpers/question_helper.rb
- app/models/user_session.rb
- app/views/pages/_training.html.erb
- app/views/questions/it_training.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/action_plan_spec.rb
- spec/features/jobs_near_me_spec.rb
- spec/features/questions_spec.rb
- spec/features/task_list_spec.rb
- spec/helpers/question_helper_spec.rb
- spec/models/user_session_spec.rb
We are treating this as a separate which
could future have additional options for IT training
as per conversation with Shelina.
This approach is also less complexity than having to
use the same :training key on the session for both
it training & training pages.
The sequence is:
Maths or English skills
IT Training - Computer skills
Job Hunting skills
https://dfedigital.atlassian.net/browse/GET-831
> Introduce IT training questions page

- config/locales/en.yml
https://dfedigital.atlassian.net/browse/GET-834
Some users believed they might be tested on their maths and english skills, so this softens the language slightly.
Check page title.
> Change title for maths and english questions page

- app/views/shared/_contact_us.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-798
> GET-798 Remove Christmas/NYE call times message

- azure-pipelines-deploy-template.yml
- azure-pipelines.yml
- azure/config/qa.parameters.json
This builds on top of the Admin Conditional deployment to enable it on QA
> Enable admin mode on qa

- app/views/shared/feedback/_survey.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-858
Rails is generating the id from the name, make them unique so the id is unique
> GET-858 Rename hidden fields to avoid duplicate ids in page

- config/initializers/active_admin.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-896
set this in the main config for all resources in active admin
> GET-896 Only allow CSV format for download

- app/models/admin_user.rb
- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
https://dfedigital.atlassian.net/browse/GET-895
> Get 895  - Make custom hostname  parameterisable for both the app and the admin area 

- azure/template.json
https://dfedigital.atlassian.net/browse/GET-873
> Add default project tags to all resources

- app/views/job_profiles/_job_profile.html.erb
Fix the following:
- Must ensure every id attribute value used in ARIA
and in labels is unique.
https://dequeuniversity.com/rules/axe/3.3/duplicate-id-aria?application=rocketvalidator
```ruby
"description": "Ensures every id attribute value used in ARIA and in labels is unique"
"help": "IDs used in ARIA and labels must be unique"
"helpUrl": "https://dequeuniversity.com/rules/axe/3.3/duplicate-id-aria?application=axeAPI"
"id": "duplicate-id-aria"
"impact": "critical"
"nodes": [
{
"all": []
"any": [
{
"data": "recent-growth-details"
"id": "duplicate-id-aria"
"impact": "critical"
"message": "Document has multiple elements referenced with ARIA with the same id attribute: recent-growth-details"
"relatedNodes": [
```
- Ensures all ARIA attributes have valid values …
> Accessibility fix: IDs used in ARIA and labels must be unique

- azure/config/uat.parameters.json
https://dfedigital.atlassian.net/browse/GET-901
Unable Admin Area on UAT environment.
> Enable admin on UAT

- app/views/job_vacancies/index.html.erb
- app/views/skills_matcher/_sort_form.html.erb
Error: the array [
{
"issues": [
{
"description": "Ensures every form element has a label"
"help": "Form elements must have labels"
https://dequeuniversity.com/rules/axe/3.3/label?application=axeAPI
Should not see the above error.
> Fix the following Axe failure:

- app/views/pages/_job_hunting.html.erb
- app/views/pages/_training.html.erb
- app/views/pages/action_plan.html.erb
- app/webpacker/styles/_action-plan.scss
When CSS is disabled the links should be at least
under the headings of each section.
https://dfedigital.atlassian.net/browse/GET-853
> Restructure Action Plan markup

- config/locales/en.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-884
> GET-884 Existing skills content change

- app/views/questions/it_training.html.erb
- app/views/questions/job_hunting.html.erb
- app/views/questions/training.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-885
Copy change on questions pages, and fix typo
> GET-885 Copy change on questions page

- app/views/skills/_job_profiles_with_skills.html.erb
- spec/features/skills_builder_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-883
> GET-883 Amend content on selected skills page

- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/template.json
https://dfedigital.atlassian.net/browse/GET-908
This PR allows passing an ipSecurityRestrictions object for each of the WebApps (app and admin) 
Uses https://github.com/DFE-Digital/get-help-to-retrain-devops/commit/6cc89a562e4973a4b73b12ceb930071892c1606e
> GET-908 Allow passing in ipSecurityRestrictions per webapp

- app/models/job_profile_search.rb
- spec/models/job_profile_search_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-926
Amend job profile search ranking. We are currently leveraging multiple things
1) Set weight on exact matches, those always precede partial matching
2) Set weight on partial matches
3) Set nil values to zero
4) sum up all partial/exact values from the following fields:
name, alternative titles, hidden titles, specialism, description
5) desc order of importance for the following fields:
name, alternative titles, hidden titles, specialism, description
6) order alphabetically after
Queries value before vs after:
~38ish ms per query vs now ~40ms
I think those values are not worth improving yet
Testing
https://get-help-to-get-926-imp-rifmre.herokuapp.com/check-your-skills/results?search=retail+assistant …
> GET-962 Amend Job profile search

- app/views/pages/_job_hunting.html.erb
- app/views/pages/_training.html.erb
- app/views/pages/action_plan.html.erb
- app/webpacker/styles/_action-plan.scss
jira-ticket: https://dfedigital.atlassian.net/browse/GET-922
* Remove content in job hunting section
* move find a course link and amend content in training section
* Add blue section separators for apply for a job section. I added
a new class which only shows from tablet view onwards so sidebar
doesn't interfere in mobile view
* Add margin 6 to all blue sections
All amendments have been checked and approved by Steve
> GET-922 Amend action plan content and styling

- app/views/job_profiles/_no_results.html.erb
- app/views/job_profiles/_search_form.html.erb
- app/views/job_profiles/results.html.erb
- config/locales/en.yml
- spec/features/skills_matcher_spec.rb
Specific job search: update head title
Specific job search results:
- update head title
- add new paragraph below search box
Specific job search - no results:
- only the content below the search box should now change
https://dfedigital.atlassian.net/browse/GET-877
> New copy changes for job profiles search

- app/views/errors/save_results_error.html.erb
- app/views/shared/_save_your_results.html.erb
- app/views/users/new.html.erb
- config/locales/en.yml
- spec/features/user_authentication_sidebar_spec.rb
- spec/features/user_registration_spec.rb
- spec/features/user_sign_in_spec.rb
- spec/features/user_sign_in_through_registration_spec.rb
Replace save your results with save your progress.
https://dfedigital.atlassian.net/browse/GET-900
> Update content for save your results journey

- app.json
- app/views/errors/return_to_saved_results_error.html.erb
- app/views/pages/cookies_policy.html.erb
- app/views/users/link_expired.html.erb
- app/views/users/return_to_saved_results.html.erb
- app/views/users/sign_in_link_sent.html.erb
- app/views/users/sign_in_link_sent_again.html.erb
- config/locales/en.yml
- spec/features/user_authentication_sidebar_spec.rb
- spec/features/user_sign_in_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-899
* Replace return to saved results with return to saved progress
* Keep urls the same for now
* Fix cookies page as well as error pages
> GET-899 Change content for returning from saved results to returning from saved progress instead.

- spec/features/user_registration_spec.rb
Fix broken specs from a bad merge.
> Fix broken specs from a bad merge

- app/views/users/new.html.erb
- app/views/users/return_to_saved_results.html.erb
Fix the following issues:
- Input field has no description
- Label control - label not associated with form control
Target pages:
- Save my progress
- Return to saved progress
https://dfedigital.atlassian.net/browse/GET-936
> Fix accessibility issues

- azure/config/prod.parameters.json
Enable admin feature on prod
- Add necessary keys on the env
https://dfedigital.atlassian.net/browse/GET-917
> Enable admin feature on prod

- app/views/shared/feedback/_survey.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-963
The aria control should have the same name as the form id
> GET-963 Add correct id to aria controls

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- app/views/pages/accessibility_statement.html.erb
- app/views/pages/information_sources.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/home_spec.rb
- spec/helpers/application_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-958
* Add accessibility statement page and link from footer
* Refactor back link for reuse
> Get-958 Add accessibility statement

- app/views/pages/privacy_policy.html.erb
- config/locales/en.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-959
* update policy content
* add back button
> GET-959 Update privacy policy

- app/views/layouts/application.html.erb
- app/views/pages/terms_and_conditions.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/home_spec.rb
Add terms and conditions page
https://dfedigital.atlassian.net/browse/GET-977
> Add terms and conditions page

- app/models/csv/course.rb
- app/models/csv/course_detail.rb
- app/models/csv/opportunity.rb
- app/models/csv/opportunity_start_date.rb
- app/models/csv/provider.rb
- app/models/csv/venue.rb
- db/migrate/20200220112538_create_csv_course_details.rb
- db/migrate/20200220114924_create_csv_providers.rb
- db/migrate/20200220132648_create_csv_opportunities.rb
- db/migrate/20200220142433_create_csv_opportunity_start_dates.rb
- db/migrate/20200220143938_create_csv_venues.rb
- db/migrate/20200220150422_create_csv_courses.rb
- db/schema.rb
This PR creates the necessary database structure to ingest the CSV Course data. This also creates the model associations that are needed as follows:
- cvs_courses - our lookup table including precalculated values
- cvs_course_details - this will contain the data from courses CSV file
- csv_providers - this will contain the data from providers CSV file
- csv_opportunities - this will contain the data from opportunities CVS file
- csv_venues - this will contain the data from venues CVS file
- csv_opportunity_dates - this will contain the data from opportunity dates CVS file
[primary_erd.pdf](https://github.com/DFE-Digital/get-help-to-retrain/files/4231683/primary_erd.pdf)
https://dfedigital.atlassian.net/browse/GET-1019
> Get 1019 create courses tables

- config/features.rb
This is just adding the flag in the configuration and
also creating the flags on Split.io
https://dfedigital.atlassian.net/browse/GET-1021
> Add the new feature flag: csv_courses

- azure/config/prod.parameters.json
- azure/config/uat.parameters.json
This IP is different than ours, as it is done through the toolkit
> Add Shelina's IP to admin interface for UAT and Prod

- Gemfile.lock
Reverts DFE-Digital/get-help-to-retrain#481
> Revert "Bump nokogiri from 1.10.5 to 1.10.8"

- app/controllers/courses_controller.rb
- app/decorators/csv/course_lookup_decorator.rb
- app/models/csv/course_geospatial_search.rb
- app/models/csv/course_lookup.rb
- app/views/courses/csv/_course.html.erb
- app/views/courses/index.html.erb
- spec/decorators/csv/course_lookup_decorator_spec.rb
- spec/features/csv/find_training_courses_spec.rb
- spec/models/csv/course_geospatial_search_spec.rb
The new page will render the new data coming from the CSV
files and it is hidden under a feature flag.
https://dfedigital.atlassian.net/browse/GET-1022
> Add the new courses listing page

- app/views/skills/_job_profiles_with_skills.html.erb
- spec/features/skills_builder_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-981
Amend link content
> GET-981 Change skills summary content

- app/views/questions/training.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-980
Amend training question first paragraph to become a list, and the details for both english and maths
> GET-980 Amend training question content

- app/decorators/job_profile_decorator.rb
- app/views/job_profiles/_apply_to_become.html.erb
- app/views/job_profiles/_skills_section.html.erb
- spec/decorators/job_profile_decorator_spec.rb
- spec/features/action_plan_spec.rb
- spec/features/job_profile_spec.rb
- spec/features/jobs_near_me_spec.rb
- spec/features/questions_spec.rb
- spec/features/task_list_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1028
* Amend last section of skills
* Amend apply to become section
* Add space at bottom of page to fix view in mobile
> GET-1028 Amend job profile page

- app/controllers/questions_controller.rb
- app/views/pages/_training.html.erb
- app/views/questions/edit_training.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/action_plan_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1019
Add different link on action plan for editing training skills.
We are maintaining the different keys in the user session for now
as well.
> GET-833 Add extra page for editing training skills

- app/views/pages/_training.html.erb
- app/views/pages/action_plan.html.erb
- spec/features/action_plan_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-957
* Amend training section by adding button instead of link for find
a course when other options selected. Amend content when no options
selected
* Amend Explore on the job training section
* Amend here's what you've done so far section
> GET-957 Amend action plan content

- app/constraints/csv_courses_constraint.rb
- app/controllers/courses_controller.rb
- app/decorators/csv/opportunity_decorator.rb
- app/models/csv/opportunity.rb
- app/models/csv/provider.rb
- app/views/courses/csv/_course.html.erb
- app/views/courses/show.html.erb
- config/features.rb
- config/locales/en.yml
- config/routes.rb
- spec/decorators/csv/course_lookup_decorator_spec.rb
- spec/decorators/csv/opportunity_decorator_spec.rb
- spec/features/csv/find_training_courses_spec.rb
- spec/routing/courses_spec.rb
Add the following formatting rules:
Price:
- For “0.00”, show “Free”
- for any other number, show the actual price
- if nil, don’t show row
Description:
- if less than 15 chars hide
- display otherwise
Start Date:
- format to %d %b %Y
End Date:
- removed for now due to too much data inconsistency
Website url:
- Courses - Booking url OR
- Courses - Url OR
- Provider - Url OR
- Venue url
Also fixing an accessibility issue on the main courses
listing page.
https://dfedigital.atlassian.net/browse/GET-1023
> Create the course description page

- app.json
- app/services/find_a_course_service.rb
- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
- config/application.rb
- spec/services/find_a_course_service_spec.rb
Add base service class for FindAJob NCS Service
This is allowing us to start working independently on the other tickets.
https://dfedigital.atlassian.net/browse/GET-1056
> Add base service class for FindAJob NCS Service

- app.json
> make find keys not necessary on heroku

- azure/config/dev1.parameters.json
> Remove keys from dev1, as we will use it as a stress test env

- app/webpacker/packs/courses-accordion.js
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1051
Add check for specific course error to open accordion on courses page
> GET-1051 Add check for error on courses page to open accordion

- app/models/course_search.rb
- spec/models/course_search_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1085
* Search by keyword math instead of maths for courses API to
get more results
> GET-1085 Search by math instead of maths for courses

- app/controllers/courses_controller.rb
- app/helpers/ga_tracking_helper.rb
- app/views/courses/_search_filter.html.erb
- app/views/courses/csv/_filter.html.erb
- config/locales/en.yml
- spec/features/find_courses_near_me_spec.rb
- spec/helpers/ga_tracking_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1050
* Track course hours if selected from dropdown and different than all
* Track course type if selected from dropdown and different than all
* Reuse the constant for the dropdown but change to hash to reverse
lookup the values for the tracking
GA qa key added to heroku app for testing
> GET-1050 Track course type and course hours

- app/views/courses/index.html.erb
Update message copy for the case when no results are found.
> Update message copy for no course results page

- app/decorators/course_details_decorator.rb
- app/decorators/search_course_decorator.rb
- app/helpers/course_helper.rb
- app/models/search_course.rb
- app/views/courses/_search_course.html.erb
- app/views/courses/show.html.erb
- spec/decorators/course_details_decorator_spec.rb
- spec/decorators/search_course_decorator_spec.rb
- spec/features/find_courses_near_me_spec.rb
- spec/helpers/course_helper_spec.rb
- spec/models/search_course_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1083
* Show start date/flexible date on results page
* Hide undefined course hours
* Format location and remove n/a values
> GET-1083 Courses near me results formatting

- lib/tasks/data_import/update_recommended_job_profiles.rake
jira-ticket: https://dfedigital.atlassian.net/browse/GET-717
Add all jobs from spreadsheet to rake task
> GET-717 Update list of non recommended jobs

- app/views/questions/it_training.html.erb
- azure/jmeter/jmeter-performance-tests.jmx
- config/locales/en.yml
- config/routes.rb
- spec/features/user_feedback_survey_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/routing/action_plan_spec.rb
- spec/routing/admin_spec.rb
- spec/routing/courses_spec.rb
- spec/routing/job_vacancies_spec.rb
Change page titles where necessary
Change URL where necessary
Don’t do anything to breadcrumbs in this ticket
https://drive.google.com/file/d/1GGfYS5LNXugi5ua5xdfvQYHmrjSDtgUl/view
> All page titles to follow the new convention

- app/controllers/job_profiles_controller.rb
- app/helpers/ga_tracking_helper.rb
- spec/features/job_profile_spec.rb
- spec/helpers/ga_tracking_helper_spec.rb
Track targetted job profile in GA
https://dfedigital.atlassian.net/browse/GET-1034
> Track targetted job profile in GA

- db/migrate/20200403100607_drop_csv_courses_tables.rb
- db/schema.rb
Cleaning up our db and removing all unused tables
after decommissioning the courses feature.
https://dfedigital.atlassian.net/browse/GET-1119
> Remove all tables from decommissioned feature

- app/views/users/registration_email_sent_again.html.erb
- app/views/users/sign_in_link_sent_again.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1071
* Fix headers to be consistent
> GET-1071 Add consistent headers on link sent again pages

- app/views/pages/information_sources.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1040
Add courses to info sources and remove apprenticeships section.
> GET-1040 Remove apprenticeships section and add courses to info sources

- app/views/job_vacancies/index.html.erb
- spec/features/jobs_near_me_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-983
* Amend title on page
* Amend content when zero results found
> GET-983 Amend content on job vacancies page

- app/views/questions/it_training.html.erb
- config/locales/en.yml
- spec/features/questions_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1081
* Amend page and page title
* Amend rest of button and content and fix specs
* I left the GA tracking alone as we won't be amending that
> GET-1081 Amend it question page content

- app/views/pages/action_plan.html.erb
- spec/features/action_plan_spec.rb
- spec/features/jobs_near_me_spec.rb
Update copy on the Action Plan page.
https://dfedigital.atlassian.net/browse/GET-1111
> Update copy on the Action Plan page

- app/views/home/index.html.erb
Change first paragraph on landing page to say “Use this service to find out other types of work you can do with your current skills. You’ll then build an action plan to fill any skill gaps you have and change jobs.”
https://dfedigital.atlassian.net/browse/GET-1026
> Copy change for landing page

- app/views/job_profiles/_brief.html.erb
- spec/features/job_profile_spec.rb
Copy update on job profiles page
https://dfedigital.atlassian.net/browse/GET-1072
> Copy update on job profiles page

- app/views/pages/task_list.html.erb
- app/views/pages/task_list_items/_item_2.html.erb
- app/views/pages/task_list_items/_item_3.html.erb
- spec/features/task_list_spec.rb
Update the copy on the Steps page
https://dfedigital.atlassian.net/browse/GET-1027
> Update the copy on the Steps page

- app/views/skills/_job_profiles_with_skills.html.erb
Increase button spacing on Skills page
https://dfedigital.atlassian.net/browse/GET-1075
> Increase button spacing on Skills page

- app/controllers/courses_controller.rb
- app/controllers/job_vacancies_controller.rb
- app/helpers/ga_tracking_helper.rb
- app/views/courses/_search_filter.html.erb
- config/locales/en.yml
- spec/features/find_courses_near_me_spec.rb
- spec/features/jobs_near_me_spec.rb
- spec/helpers/ga_tracking_helper_spec.rb
Track the following filters:
- outcode of the searched postcode
- the distance filter
Also track the distance filter on Courses page for
consistency.
https://dfedigital.atlassian.net/browse/GET-1150
> Add GA tracking to Jobs Near Me page

- app/views/pages/task_list_items/_item_3.html.erb
Update copy on Steps page
https://dfedigital.atlassian.net/browse/GET-1153
> Update copy on Steps page

- app/controllers/job_profiles_controller.rb
- app/views/job_profiles/skills/index.html.erb
- spec/features/skills_builder_spec.rb
Do not downcase job profile names
https://dfedigital.atlassian.net/browse/GET-827
> Do not downcase job profile names

- app/views/job_profiles/skills/index.html.erb
- app/views/pages/action_plan/_selected_skill.html.erb
- app/views/skills/_skill.html.erb
Capitalize all user selected skills
https://dfedigital.atlassian.net/browse/GET-1154
> Capitalize all user selected skills

- app/views/pages/cookies_policy.html.erb
Replace breadcrumbs on the Cookies page
https://dfedigital.atlassian.net/browse/GET-1100
> Replace breacrumbs on the Cookies page

- app/webpacker/styles/_links.scss
- app/webpacker/styles/application.scss
Use fit-content width for focus on links
https://dfedigital.atlassian.net/browse/GET-881
> Use fit-content width for focus on links

- lib/tasks/data_import/update_recommended_job_profiles.rake
Add new jobs on the list of not recommended
https://dfedigital.atlassian.net/browse/GET-1157
> Add new jobs on the list of not recommended

- app/views/courses/show.html.erb
- app/views/errors/course_postcode_search_error.html.erb
- app/views/errors/courses_near_me_error.html.erb
- app/views/errors/jobs_near_me_error.html.erb
- app/views/errors/save_results_error.html.erb
- app/views/home/index.html.erb
- app/views/shared/_cookies_banner.html.erb
- app/views/shared/feedback/_survey.html.erb
- app/views/skills/_job_profiles_with_skills.html.erb
- app/views/users/registration_email_sent_again.html.erb
- app/views/users/registration_results_saved.html.erb
This comes as a recommendation from the DAC report.
Make links with button role not draggable
https://dfedigital.atlassian.net/browse/GET-949
> Make links with button role not draggable

- app/views/admin/user_sessions/sign_in.html.erb
- app/views/layouts/admin/application.html.erb
- config/locales/en.yml
Update copy on the Admin page
https://dfedigital.atlassian.net/browse/GET-870
> Update copy on the Admin page

- app/views/pages/cover_letter_advice.html.erb
- app/views/pages/cv_advice.html.erb
- app/views/pages/interview_advice.html.erb
Update content on all 3 job hunting advice pages
cv-advice, cover-letter-advice, interview-advice
https://dfedigital.atlassian.net/browse/GET-941
> Get 941 copy changes

- app/views/shared/_contact_us.html.erb
- config/locales/en.yml
Update the adviser partial copy
https://dfedigital.atlassian.net/browse/GET-968
> Update the adviser partial copy

- app/views/errors/course_postcode_search_error.html.erb
- app/views/errors/courses_near_me_error.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/jobs_near_me_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/return_to_saved_results_error.html.erb
- app/views/errors/unprocessable_entity.html.erb
This causes an accessibility issue reported
by Siteimprove.
https://dfedigital.atlassian.net/browse/GET-967
> Remove duplicate IDs on all error pages

- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
- config/application.rb
- config/initializers/content_security_policy.rb
Add CSP header to protect against XSS
This is one of the recommendations coming from
the Pen Test report.
Useful resources:
https://guides.rubyonrails.org/security.html#content-security-policy
https://bauland42.com/ruby-on-rails-content-security-policy-csp/
https://medium.com/@likeuwill_44358/ruby-on-rails-6-and-content-security-policy-csp-42e1e8ed86a
https://dfedigital.atlassian.net/browse/GET-744
> Protect agains XSS by adding a CSP header

- README.md
Correct documentation small error
> Correct documentation small error

- app/views/layouts/application.html.erb
The service is being decommissioned and users need to be let now in advance.
> Add service decommission banner
