- app/models/category.rb
- app/models/job_profile.rb
- app/models/job_profile_category.rb
- app/models/job_profile_skill.rb
- app/models/skill.rb
- db/migrate/20190614101226_create_job_profiles.rb
- db/schema.rb
As per description
Added a few specific attributes to job profile to support things we might want to display in a search results page - most other things will be scraped and rendered as a `content` block of html. Also added `recommended` attribute to support future opinionated search results.
Skills have only a unique `name` attribute. Job profile and categories have a unique `slug` attribute representing part of the original url they were scraped from.
> Initial simple data model to support persisting job profiles and related info

- Dockerfile
- README.md
- azure-pipelines.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-49 
* Docker image now builds test dependencies (needs rethink)
* Add azure pipeline to run tests and build images per commit and tag with build number and Git SHA
* If this is master is will build without cache and with the tag: latest
* If build is successful it will push images to DockerHub
* Things to look out for:
- link is deprecated, could we use docker-compose instead?
- could not make use of service containers as network would not allow connections properly
- using separate jobs for testing and deploy (deploy job) did not allow us to share the image build 
meaning we had to rebuild it, so for now everything is in a single job
> GET-49 Set up CI with Azure Pipelines

- Dockerfile
To include all our assets correctly, set NODE_ENV to production so when assets are compiled for deploy they are under the right environment
> Make sure assets are compiled under production environment

- Dockerfile
Images from node modules are included under different directory
include that when porting assets to final container
> Include assets folder as well as packs

- azure-pipelines.yml
We want to use the last commit (short) sha to identify our builds. 
Use the short sha of the last commit (head)
> Use last commit sha

- azure-pipelines.yml
We are having duplicate builds because we build on every branch. On PRs we get a build for the branch and also for the PR event.
Don't trigger builds on PRs
> Skip builds for PRs

- azure/template.json
https://dfedigital.atlassian.net/browse/GET-156
This PR creates the Azure Application Insights resource that the application will send data to.
It also exposes the `Instrumentation Key` dynamically to the running container via the `APPINSIGHTS_INSTRUMENTATIONKEY` environment variable. 
This can be approved and merged before the application is ready to send metrics, as it just creates the monitoring namespace and an authentication token to it.
> GET-156 Add Azure Application Insights to the application

- app/helpers/job_profiles_helper.rb
- app/views/job_profiles/show.html.erb
- app/views/skills/index.html.erb
- spec/helpers/job_profiles_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-138
* Pages which come back from a search will now allow a user to
maintain their search results
* Job profile page will now allow you to either go back to a
profile or a search results page.
> GET-138 Allow job profile to show paths from results or categories

- Gemfile
- app/decorators/job_profile_decorator.rb
- azure-pipelines.yml
- config/spring.rb
- features/step_definitions/test_steps.rb
- features/support/env.rb
Fixes rubocop violations and adds a step to Azure pipeline so that we can use rubocop locally. The gov.uk linter seems to ignore a lot of violations so this is more thorough.
Ignored class length and line length violations in JobProfileDecorator for now - that will be refactored over time to resolve those.
Check build passes - examine Azure devops output.
```
##[section]Starting: Rubocop linter
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line …
```
> GET-136 rubocop

- app/helpers/job_profiles_helper.rb
- app/views/categories/_results_list.html.erb
- app/views/categories/show.html.erb
- app/views/check_your_skills/_results_list.html.erb
- app/views/check_your_skills/index.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/explore_occupations/index.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/job_profiles/show.html.erb
- app/views/pages/find_training_courses.html.erb
- app/views/pages/next_steps.html.erb
- app/views/pages/task_list.html.erb
- app/views/shared/search/_results_list.html.erb
- app/views/skills/index.html.erb
- config/locales/en.yml
- spec/helpers/job_profiles_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-138
* users don't want to go back home but to tasklist from all pages
* keep home on task list breadcrumbs
* remove title of job and only have job details instead
* Move results list to specific directories to avoid confusion
as now we are being explicit with passing params around
* Change breadcrumbs helper to rely on params rather than referrer
request as that was flakey and not explicit causing unexpected
behaviour from outside requests and if someone presses the back
button on the browser
Breadcrumbs paths we support now (this is not the exact content but just to show the paths):
1) Homepage: none
2) Task list page: Home > Task list
3) Check your existing skills page: Home: Task list > Check your skills
4) Check your existing …
> Get 138 fix breadcrumbs

- Gemfile
- Gemfile.lock
- app/decorators/job_profile_decorator.rb
- app/models/job_profile.rb
- app/scrapers/job_profile_scraper.rb
- config/application.rb
- config/locales/en.yml
- db/migrate/20190626115718_add_salary_range_to_job_profiles.rb
- db/schema.rb
- spec/decorators/job_profile_decorator_spec.rb
- spec/models/job_profile_spec.rb
- spec/scrapers/job_profile_scraper_spec.rb
Salary range was previously rendered on the fly using Nokogiri to parse the job profile body content. This was too slow when viewing a large number of job profiles on the search results page.
Added new attributes to job profile for salary min and max values. These are populated when scraping the job profile, and then used within the decorator. Also cleaned up a little related/dead code.
As the salary values are held as integers, they need to be reformatted back to currency values. I've changed the default locale to `en-GB` to accomodate this, otherwise we would need to specify currency symbol every time. Open to other approaches though.
Search results page (for all 857 jobs) is now nice and quick:
```
Rendering explore_occupations/results.html.erb within layouts/application
Rendered …
```
> GET-141 scrape salary range

- app/models/job_profile.rb
- spec/models/job_profile_spec.rb
Given I search for a keyword that already exists among Skills/Occupation, e.g `Music therapist`
When I add accidental spaces (no matter the position)
Then I get no results.
AC
Ensure our search keywords are stripped of any additional spaces.
When I search for `Music therapist` or ` Music therapist` or `Music   therapist` I should get the same results.
https://dfedigital.atlassian.net/browse/GET-168
> Ensure accidental spaces are ignored at search

- app/views/pages/task_list.html.erb
Accidentally added home: `Home: Get help to retrain` instead of `Home` on tasklist. This is the only page that should link back to home
> On task list keep home breadcrumb

- README.md
- app/models/job_profile.rb
- lib/tasks/data_import/refresh_job_profiles.rake
This is much faster than re-scraping the entire set of job profiles from NCS again - taking around 10 seconds rather than 15 minutes. It's just a hacky thing so haven't added specs but tested locally and works well.
Allowed `scraper` to be injected into job profile `scrape` method, which allows preloading the Wombat scraper with the stored `content`.
Run `bundle exec rails data_import:refresh_job_profiles` - this will populate `salary_min` and `salary_max` columns if the job profiles were scraped prior to GET-141 being merged.
> Add a new rake task to update job profile attributes with previous content

- Dockerfile
- Gemfile
- Gemfile.lock
- app/controllers/categories_controller.rb
- app/helpers/application_helper.rb
- app/helpers/explore_occupations_helper.rb
- app/views/categories/show.html.erb
- app/views/check_your_skills/index.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/explore_occupations/index.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/home/index.html.erb
- app/views/job_profiles/show.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/find_training_courses.html.erb
- app/views/pages/next_steps.html.erb
- app/views/pages/task_list.html.erb
- app/views/skills/index.html.erb
- azure/template.json
- config/initializers/application_insights.rb
- config/locales/en.yml
- spec/helpers/application_helper_spec.rb
https://dfedigital.atlassian.net/browse/GET-156
This adds a javascript snippet to every page in `production` which collects data on every page impression served. It also creates a permanent user cookie and temporary session cookie to track repeat visits.
* Adding the gem and initialiser boilerplate for Azure application insights.
* Introduced page titles for each view to allow easier tracking of user journeys within app insights
* Use category slugs rather than id's for category paths so that these don't change after scraping new categories
This needs to be deployed to an Azure instance with a reasonable level of traffic to allow testing - there's also some lead time before data appears. I'd suggest we merge this and then evaluate how well it works with the updated page titles.
> GET-156 Business metrics (KPIs)

- app/decorators/job_profile_decorator.rb
- app/helpers/job_profiles_helper.rb
- app/scrapers/job_profile_scraper.rb
- app/views/categories/_results_list.html.erb
- app/views/check_your_skills/_results_list.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/job_profiles/_brief.html.erb
- db/migrate/20190701155237_add_alternative_titles_to_job_profiles.rb
- db/schema.rb
- spec/decorators/job_profile_decorator_spec.rb
- spec/helpers/job_profiles_helper_spec.rb
- spec/scrapers/job_profile_scraper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-169
* When scraping job profile pages Persist alternative titles in the database in an array column
* Remove sub hero content from Job Profile decorator
* Add alternative titles lists in check your skills and explore occupations search results
* Substitute alternative titles for sub hero content in Job Profile page
* fix some styles where we are missing some margins
> GET-169 Add Alternative Titles

- Gemfile
- Gemfile.lock
- azure/template.json
- config/environments/production.rb
This is a short term solution until we move to a native Azure logging approach.
I've added support for an optional `LOGGLY_TOKEN` environment variable. If this is set, then loggly is used as the preferred logger, with all log traffic captured and forwarded.
> Add loggly for production logging

- app/views/layouts/application.html.erb
- app/webpacker/packs/application.js
- app/webpacker/packs/search-form.js
- package.json
- yarn.lock
Turbolinks is intended to improve page load times, by avoiding the need to fetch and parse CSS and JS assets described in the `head` section of the page. In practice this works to a degree, but has complications.
Already we have had to adapt the progressive enhancement for search to listen to custom turbolinks events. The Azure App Insights tracking script is working intermittently since this is only firing on initial page load or manual refresh, not when user navigates to a new page by clicking links.
There are numerous anecdotal reports of various issues with the library, including double loading of pages, accessibility limitations etc. Overall, it's not adding value so good to remove.
Completely remove turbolinks library and any associated setup. Use standard window load event to hook …
> GET-183 Remove Turbolinks

- app/views/layouts/application.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-174
Add a X-Robots-Tag to all pages to stop search engines indexing pages.
Specifications for this tag are found here:
https://developers.google.com/search/reference/robots_meta_tag
and GovUK recommendation:
https://www.gov.uk/service-manual/technology/get-a-domain-name
> GET-174 Disable indexing on all pages in beta release

- Dockerfile
This PR fixes a now mandatory use of `--force` on `bundle install --clean`
> --force is now mandatory on bundle install --clean

- Gemfile
- Gemfile.lock
- app/controllers/check_your_skills_controller.rb
- app/controllers/explore_occupations_controller.rb
- app/views/check_your_skills/results.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/webpacker/images/icon-pagination.svg
- app/webpacker/styles/_pagination.scss
- app/webpacker/styles/application.scss
- config/initializers/kaminari_config.rb
- config/locales/en.yml
- spec/features/check_your_skills_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-101
* Use Kaminari gem to paginate results pages for both check your skills and explore occupations search
* Add Kaminari views and edit styles according to HMRC pagination:
http://hmcts-design-system.herokuapp.com/components/pagination
This has been reviewed by Steve and approved to be used. So disregard ticket stylings
This is deployed to for review: 
https://s108d02-dev-as.azurewebsites.net/check_your_skills/results?utf8=%E2%9C%93&name=e
https://s108d02-dev-as.azurewebsites.net/explore_occupations/results?utf8=%E2%9C%93&name=ex
> GET-101 Add Pagination

- app/views/layouts/application.html.erb
- app/views/pages/task_list.html.erb
- app/webpacker/packs/application.js
- app/webpacker/packs/search-form.js
- app/webpacker/packs/track-events.js
- spec/features/task_list_spec.rb
Adding client-side tracking for when the user clicks both of the User Exit Survey links. 
Tracking done inside AppInsights
https://dfedigital.atlassian.net/browse/GET-211
> Add client side tracking for User Exit Survey Link

- app/controllers/check_your_skills_controller.rb
- app/controllers/explore_occupations_controller.rb
- app/helpers/job_profiles_helper.rb
- app/views/check_your_skills/_results_list.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/search/_results_form.html.erb
- app/views/skills/index.html.erb
- spec/features/check_your_skills_spec.rb
- spec/features/explore_occupations_spec.rb
- spec/helpers/job_profiles_helper_spec.rb
We should use the same query string across all searches and
breadcrumbs. Switch name to search in form input,
breadcrumbs and all tests.
Also add tests for pagination for explore occupations which were
missed last time
deployed to https://s108d01-dev-as.azurewebsites.net/ for testing
> Change query params from name to search across all forms/breadcrumbs

- azure-pipelines.yml
- spec/features/check_your_skills_spec.rb
- spec/features/explore_occupations_spec.rb
- spec/rails_helper.rb
- spec/support/capybara.rb
* Set default Capybara driver to selenium headless chrome
* Add container for selenium standalone chrome to run as a service in CI
* When running in CI, set Capybara chrome driver to read from remote selenium chrome url running in container
* Pass in docker bridge ip to allow selenium chrome container access to the running instance
* Add missing JS tests for check your skills and explore occupations
> Add Javascript RSpec Feature Support and missing tests

- Gemfile
- Gemfile.lock
- app/models/course.rb
- app/models/course_geospatial_search.rb
- app/validators/postcode_validator.rb
- config/initializers/geocoder.rb
- db/migrate/20190719081758_add_geocode_columns_to_courses.rb
- db/schema.rb
- spec/models/course_geospatial_search_spec.rb
- spec/models/course_spec.rb
- spec/rails_helper.rb
- spec/support/geocoder.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-123
* Add latitude longitude columns to courses table to allow geocoding of postcodes of courses
* Validate postcode on course model against uk postcodes
* Format postcode on course model against uk postcodes to be in capital letter format, and a space in the middle
* Add callback to geocode the postcodes after validation on courses model. This means latitude and longitude values will be populated by the Geocoder gem
* Add method to return courses ordered by distance to an address
* Distance can be defined and defaults to 5 miles
* Validate address before geocoding and performing a geospatial
query to get all courses within the distance defined
* Return custom errors for invalid address and Geocoder API errors  so we can create …
> GET-123 Add Geocoding to Courses

- app/admin/categories.rb
- app/admin/dashboard.rb
- app/admin/job_profiles.rb
- app/admin/skills.rb
These seem to be causing issues with bootsnap in production; that is eager loading all of the ruby code so tries to reference the admin pages, which in turn reference `ActiveAdmin` which is not installed in the production bundle. Added guards around each of these to ensure they are only parsed if the gem is installed.
> Ensure that active admin custom pages are not loaded outside dev mode

- azure/config/dev2.parameters.json
- azure/config/dev3.parameters.json
- azure/config/test.parameters.json
Dev environments all share the same vault entry. Test environment has a different vault with a custom key name, but is actually the same API token as dev.
For production another vault entry will be added, but not until that environment has been migrated across to the new config approach.
> Add splitApiKey configs for dev and test environments

- README.md
- app/admin/courses.rb
- app/admin/dashboard.rb
- app/admin/job_profiles.rb
- app/admin/skills.rb
- app/services/courses_service.rb
- db/migrate/20190724160424_add_enabled_to_skills.rb
- db/schema.rb
- lib/tasks/data_import/sample_courses.rake
Adds `enabled` attribute for skills, improves admin pages functionality and courses data setup.
* New `enabled` attribute for skills will be used during the forthcoming spike to explore use of skills for matching job profiles. We know that not all of the skills will be used for this, so this adds the ability to disable some of those. This capability won't be used programatically yet, but adding the column allows the data to be setup in advance and exposed via the admin interface.
* Improved data export (CSV) for job profile and skills in admin pages. Now includes a list of job profiles for each skill, and skills for each job profile. Some additional tweaks to achieve that without N+1 query issues.
* Added a rake task and some docs around setting up sample course data
* Added courses to …
> Get 233 enable skills admin

- spec/features/course_overview_pages_spec.rb
Introducing feature flagging capability seems to
have made some of our specs intermittently fail.
We need to enforce the feature is ON for those specs.
> Fix intermittent spec failures

- spec/features/find_training_courses_spec.rb
- spec/features/location_eligibility_spec.rb
- spec/models/course_geospatial_search_spec.rb
- spec/models/course_spec.rb
The test was failing with
```
NoMethodError:
undefined method `[]' for nil:NilClass
```
where in the gem file `geocoder-1.5.1/lib/geocoder/results/base.rb`:
```
def coordinates
[@data['latitude'].to_f, @data['longitude'].to_f]
end
def latitude
coordinates[0]
end
def longitude
coordinates[1]
end
```
Running bisect on the rspec seed yields the following:
```
The minimal reproduction command is:
rspec ./spec/features/location_eligibility_spec.rb[1:5] ./spec/models/course_spec.rb[1:1:1] -b --seed 20702
```
This shows us that the geocoder stub is being leaked across tests where https://github.com/DFE-Digital/get-help-to-retrain/blob/master/spec/features/location_eligibility_spec.rb#L53 is  being read instead of the default test stub.
When calling `Geocoder.coordinates` vs ActiveRecord geocoder …
> Fix flakey test that fails because of Geocoder gem ActiveRecord/normal coordinates stub

- app/controllers/pages_controller.rb
- app/views/errors/postcode_search_error.html.erb
- app/views/pages/location_ineligible.html.erb
- config/brakeman.ignore
- config/locales/en.yml
- config/routes.rb
- spec/features/location_eligibility_spec.rb
- spec/routing/location_eligibility_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-39
Add location ineligible page, when there are no courses close to user, which allows user to go to task list page anyway. based on https://get-help-to-retrain-prototype.herokuapp.com/main/release2_e2e_v2/location_ineligible
Also add error page incase API is down on the location eligibility path, we are still holding off on that one on the courses path as designs/journey not ready
ready to test on: https://dev2.nrs-ghtr.org.uk/
> GET-39 Location Ineligible page

- app/controllers/application_controller.rb
- app/controllers/check_your_skills_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/explore_occupations_controller.rb
- app/controllers/pages_controller.rb
- config/initializers/application_insights.rb
- config/locales/en.yml
This uses asynchronous telemetry client channel so doesn't block main thread - takes a few seconds for events to show up in Azure Application Insights but works well. Refactored relevant controllers very slightly to make extracting the key search param a little neater / DRY.
Easiest to test once deployed to a dev environment.
Search for job titles in check your skills and explore careers pages.
Search for postcode in courses page.
Ensure that custom events are recorded in Azure Application Insights
> Add custom track events for postcode and job searches

- Dockerfile
- azure-pipelines.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-281
* Download RVM to use our own ruby version 2.6.3
* Add path to other tasks with: `[task.prependpath]` as profile/bashrc loaded in other tasks reads from readonly system profile/bashrc
* Move tests out of docker build to run on box
* Add caching for bundle step. Unfortunately the caching step does not return the bin files as executables and loses the symlinks. So we have a step to allow binary file mods to be changed. Also note that bundle always runs as (there is no condition to say it doesn't run with caching is restored), this is to restore the correct symlinks. 
Bundle running again does not cause any slowness if caching is restored so it is ok until caching is fixed.
Build time now is ~9 minutes as opposed to ~15 minutes …
> GET-281 Imrpove CI build time

- azure-pipelines.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-279
* Create new docker image for first stage of docker build called assets
* Use this image as a cache to build first target for assets
* Use two images as cache for building the full image to utilise caching correctly as we cannot retain local cache for host agents across builds. 
reference article: https://andrewlock.net/caching-docker-layers-on-serverless-build-hosts-with-multi-stage-builds---target,-and---cache-from/#summary
removes ~2 minutes from build on a cache hit
> GET-279 Use target image to improve docker caching

- app/views/job_profiles/show.html.erb
- spec/features/explore_occupations_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-332
Feature flag training hub link in job profiles to link to new page
if course directory feature enabled
> GET-332 Fix training hub link in job profiles

- app/lib/flipflop/split_client_strategy.rb
- spec/lib/flipflop/strategies/split_client_strategy_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-333
Rescue from SplitIO connection errors and default to all features
being false if we fail to connect to the API.
> GET-333 Make sure SplitIO does not fall over if it cannot connect

- azure-pipelines.yml
This PR is an attempt to dereference a variable that moved between variable groups.
We don't really need it, and all other projects have the docker organization name hardcoded as part of the image, so there is also not much point in having the indirect reference.
This might help fix the build pipeline.
> De-reference variable

- app/controllers/job_profiles_skills_controller.rb
- app/controllers/skills_controller.rb
- app/models/skills_builder.rb
- app/views/job_profiles/skills/index.html.erb
- app/views/skills/index_v2.html.erb
- app/webpacker/styles/_skills-builder.scss
- app/webpacker/styles/application.scss
- config/features.rb
- config/locales/en.yml
- config/routes.rb
- spec/features/check_your_skills_spec.rb
- spec/features/skills_builder_spec.rb
- spec/models/skills_builder_spec.rb
- spec/routing/skills_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-231
Add Skills Builder as a feature flagged service. Users get to this page from the check your skills results page, after clicking on any job. 
To allow this new behaviour a service object: skills builder takes in skill ids selected and adds them to the user session. The skills builder validates if any skills are selected and if not returns the appropriate validation message. The skills builder also returns the list of ids of selected by user to be used in the checkboxes themselves to maintain what the user selected/didn't select
deployed for testing: https://dev3.nrs-ghtr.org.uk
> GET-231 Skills Builder

- app/controllers/job_profiles_skills_controller.rb
- app/controllers/skills_controller.rb
- app/models/skills_builder.rb
- app/views/job_profiles/skills/index.html.erb
- spec/features/skills_builder_spec.rb
- spec/features/task_list_spec.rb
- spec/models/skills_builder_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-363
When a user navigates to a job profile and selects a list of skills, the scope of those skills are only to the job profile. If a user navigates back to the search results and picks a different job profile, they should see all skills ticked unless they have visited that page before. Moving towards a skills scoped to a job profile we make it easier to move to the skill builder v2 which will now only require FE changes only.
Note that because sessions change the format of hashes to JSON, all ids are changed to strings to make things consistent throughout
ready to test on https://dev2.nrs-ghtr.org.uk
> GET-363 Separate different job profiles in skill builder

- azure-pipelines.yml
Update the build name on first stage.
The pipeline name is not being updated on first stage, so it keeps the internal ID until stage 'build'
> Update the build name on first stage

- app/decorators/job_profile_decorator.rb
- app/views/job_profiles/_highlights.html.erb
- app/views/job_profiles/show.html.erb
- app/views/shared/_boost_job_prospects.html.erb
- app/webpacker/images/arrow_falling.svg
- app/webpacker/images/arrow_growing.svg
- app/webpacker/images/arrow_growing_strongly.svg
- app/webpacker/images/arrow_stable.svg
- app/webpacker/styles/_job-profile.scss
- config/locales/en.yml
- spec/decorators/job_profile_decorator_spec.rb
- spec/factories/job_profiles.rb
- spec/features/explore_occupations_spec.rb
We've got 4 different growth icons marking the growth prospects
depending on the growth metric as follows:
n ≤ -5 - falling
-5 < n ≤ 5 - stable
5 < n ≤ 50 - growing
n > 50 - growing strongly
Also redesign the highlights section on the same page.
https://dfedigital.atlassian.net/browse/GET-317
> Add the growth icon on the job profile details

- app/views/check_your_skills/results.html.erb
- app/views/courses/_course.html.erb
- app/views/courses/index.html.erb
- app/views/explore_occupations/results.html.erb
- app/views/home/index.html.erb
- app/views/pages/location_eligibility.html.erb
- app/views/pages/next_steps.html.erb
- app/views/pages/training_hub.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/search/_results_form.html.erb
- app/webpacker/styles/_job-profile.scss
- config/locales/en.yml
- spec/features/check_your_skills_spec.rb
- spec/features/explore_occupations_spec.rb
Adding a few copy & design changes as follows:
- landing page copy changes
- location eligibility copy changes
- search form redesign
- skills results page
- occupations results page
- training hub page
- course results page
- next steps page
https://dfedigital.atlassian.net/browse/GET-316
> Overall copy & design changes

- app/controllers/skills_controller.rb
- app/controllers/skills_matcher_controller.rb
- app/decorators/job_profile_decorator.rb
- app/models/skills_matcher.rb
- app/views/job_profiles/show.html.erb
- app/views/pages/task_list.html.erb
- app/views/skills/index_v2.html.erb
- app/views/skills_matcher/_job_matches.html.erb
- app/views/skills_matcher/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/decorators/job_profile_decorator_spec.rb
- spec/features/skills_matcher_feature.rb
- spec/features/skills_matcher_spec.rb
- spec/features/task_list_spec.rb
- spec/models/skills_matcher_spec.rb
- spec/routing/skills_matcher_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-232
Add skill matcher, which accepts a session with a set of skills, and optionally a job profile id to scope to for version 1.
If there is no job profile id, the skills matcher finds all job profile ids matching those skills, and groups them by skills matched count of job profiles as a subquery.
Then by grouping on the count of skills matched we get all job profile ids that have the same
score, and order them in ascending order of name, as well as on frequency. Finally we select
the records scoped to the fields needed and expand the ids of the ordered group maintaining
ordinality.
For the score we create a new hash from the ids and calculate the score mapped to a job profile id.
The scoring system chosen counts the skills matched …
> GET-232 skill matcher

- app/views/courses/_course.html.erb
- app/views/pages/next_steps.html.erb
- app/views/pages/training_hub.html.erb
- app/views/shared/_what_you_can_do_next.html.erb
Following fixes:
1. second paragraph should have small text: https://qa.nrs-ghtr.org.uk/training-hub
https://get-help-to-retrain-prototype.herokuapp.com/main/release2_e2e_v3/training_hub
2. Fix indentation in: https://github.com/DFE-Digital/get-help-to-retrain/pull/130/files#diff-235f0713347955c73fe1258944294858R4 and close tag in: Cost: Free
3. Further help to find work on https://qa.nrs-ghtr.org.uk/courses/maths has body instead of text
4. Copy in find an apprenticeship is different on https://get-help-to-retrain-prototype.herokuapp.com/main/release2_e2e_v3/next_steps than https://qa.nrs-ghtr.org.uk/next-steps
> HOTFIX: Minor indentation + copy fixes

- README.md
- app/models/job_profile.rb
- app/models/skills_matcher.rb
- lib/tasks/data_import/update_recommended_job_profiles.rake
- spec/factories/job_profiles.rb
- spec/models/job_profile_spec.rb
- spec/models/skills_matcher_spec.rb
- spec/tasks/update_recommended_job_profiles_spec.rb
https://dfedigital.atlassian.net/browse/GET-226
Other than 54 job profiles that have been identified, all other job profiles are recommended. The 54 identified are excluded as they require a degree level qualification. Excluded jobs will still be included in the search results for "Check your skills" and skills builder so no code changes have been made there. Explore careers is about to be retired in favour of skill matcher so no changes have been made there either.
Excluded jobs don't appear in the skill matcher results, but remain elsewhere.
Run the rake task locally as described in the README - this will set `recommended` to true for all job profiles except the ones listed in the spreadsheet linked to this Jira task: https://dfedigital.atlassian.net/browse/GET-304
This can be checked …
> Add rake task to correctly set recommended flag for all job profiles

- app/controllers/courses_controller.rb
- app/views/errors/course_postcode_search_error.html.erb
- config/routes.rb
- spec/features/find_training_courses_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-319
When Postcodes.io API is down, show error page on course searching through
postcode
> GET-319 Add error page when postcodes.io api is down on course search page

- app/controllers/skills_controller.rb
- spec/features/skills_builder_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-357
This is to guard against users deep linking to skills selected without
parameters for job profile or skills selected in session
> GET-364 Redirect back to task list path if no job profile and skills selected

- app/views/check_your_skills/results.html.erb
- app/views/shared/search/_no_results.html.erb
- app/views/shared/search/_results_form.html.erb
- spec/features/check_your_skills_spec.rb
- spec/features/explore_occupations_spec.rb
The Skills page has been redesigned and the search form
was removed from the results page causing an issue when
the searched skill has no results, as the user has no way to
search again.
https://dfedigital.atlassian.net/browse/GET-365
> Fix broken UX journey caused page redesign

- app/views/courses/_course.html.erb
- app/views/shared/training_hub/_maths.html.erb
- config/locales/en.yml
Only some courses are free; revised wording as per ticket but left the copy on training hub page as is. The wording on there is softer and doesn't imply all courses are free. No tests broke as a result, so no corresponding spec changes.
* Check that individual courses don't show "Cost: Free" in the course list pages
* Check that side bar on job details page doesn't include "free"
> Removed copy which suggests all courses are free

- .rubocop.yml
- app/controllers/skills_controller.rb
- config/locales/en.yml
Keep track of which skills are selected in skills matcher.
https://dfedigital.atlassian.net/browse/GET-309
This uses Job slug for custom dimension key, with an array of skill id's as the value. This was tried with skill names but the text ends up extremely long and unreadable within AAI (we don't have any other skill attributes!). Skill id's can be correlated with skills by exporting the skills from active admin.
Tracking implementation needs a wholescale refactor to support testing; for now (due to time constraints) this does not have coverage but will be addressed soon.
Jira ticket suggests an original approach of making one tracking call for each skill; after further consideration this does not feel like a scalable approach, particularly when we move to skills builder v2 which allows …
> Add custom event tracking for selected skills in skills builder

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/skills_matcher_controller.rb
- app/models/user_session.rb
- app/views/pages/next_steps.html.erb
- app/views/pages/task_list.html.erb
- app/views/pages/task_list_items/_body.html.erb
- app/views/pages/task_list_items/_item_1.html.erb
- app/views/pages/task_list_items/_item_2.html.erb
- app/views/pages/task_list_items/_item_3.html.erb
- app/views/pages/task_list_items/_item_4.html.erb
- app/views/pages/task_list_items/_item_5.html.erb
- app/webpacker/styles/_task-list.scss
- config/locales/en.yml
- spec/features/skills_matcher_spec.rb
- spec/features/task_list_spec.rb
- spec/models/user_sessions_spec.rb
- spec/requests/pages_spec.rb
We want to have user unlock the sections on our platform
once they've went to a certain flow as follows:
'CAN’T START YET' status shown on tasklist page
on all tasks except section 1.
‘CAN’T START YET’ removed from section two once user
has clicked on ‘Find out what you can do with
these skills’ CTA on selected skills page.
‘CAN’T START YET’ removed from sections 3,4,5  after user has
clicked on ‘Find a training course’ or ‘Other ways to change jobs’
CTAs on the job descriptions page.
The state of user progress is stored on the session.
https://dfedigital.atlassian.net/browse/GET-291
> Foundation for user completion journey

- azure-pipelines.yml
The slot might not be ready from the previous task, so we need to keep retrying (with a limit)
> Add retry with limit

- azure-pipelines.yml
Revert powershell command because retry is not available on PowerShell 5.1.
We need some sort of retry.
> Revert powershell command because retry is not available

- app/controllers/check_your_skills_controller.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-307
Use kaminari pagination via array rather than db query with offsets and ordering, as that is creating surprising behaviour in text search and messes with the ordering of the query itself and introduces duplicates.
This has no implications on performance either.
Ready to test on: https://dev1.nrs-ghtr.org.uk/task-list
> GET-307 Change pagination to read from array rather than perform a db query

- app/controllers/application_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/job_profiles_skills_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/skills_controller.rb
- app/models/skills_builder.rb
- app/models/user_session.rb
- spec/models/skills_builder_spec.rb
- spec/models/skills_matcher_spec.rb
- spec/models/user_sessions_spec.rb
- spec/rails_helper.rb
- spec/support/session_helper.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-383
*  Move postcodes session read/write into user session
* Encapsulate job_profile_skills logic in user session rather than skills builder
* Rearrange user session methods per logic
* Add versioning to user_session:
-  If user has existing session it is reset pre version
- If user has existing session after versioning is set it remains intact
- If skills builder switched between v1 and v2 session is reset
- Add helper class for sessions as destroy method does not work on hashes
- Fix up all tests that include sessions to work with versions
> GET-383 user session

- spec/models/skills_matcher_spec.rb
Add logging for the query instead of the skills, as we have received
a failure with the skills logged and they seem correctly linked to
the job profiles.
Logging the query might indicate further information to help our debugging
We are also logging the collation just incase this might be an issue as well
> Remove old logging as it yielded unsatisfactory results

- app/controllers/pages_controller.rb
- app/controllers/user_personal_data_controller.rb
- app/models/user_personal_data.rb
- app/views/pages/location_ineligible.html.erb
- app/views/user_personal_data/_form.html.erb
- app/views/user_personal_data/index.html.erb
- config/features.rb
- config/initializers/custom_errors.rb
- config/locales/en.yml
- config/routes.rb
- db/restricted_migrate/20190909134904_create_user_personal_data.rb
- db/restricted_schema.rb
- spec/features/location_eligibility_spec.rb
- spec/features/your_information_spec.rb
- spec/requests/user_personal_data_spec.rb
- spec/routing/your_information_spec.rb
This feature is enabling us to capture personal
information about our users.
A couple of technical details:
1. The radio_button rails helper method wraps the
component with a div with class: field-with-errors breaking
the UI. We want to prevent this behaviour.
Here's a few resources around this:
https://stackoverflow.com/questions/22209855/radio-buttons-on-form-not-rendering-correctly-after-form-validation-failure-boo
The CSS approach won't solve the issue. Overriding approach:
From default behaviour:
```ruby
ActionView::Base.field_error_proc = Proc.new{ |html_tag, instance|
"<div class=\"field_with_errors\">#{html_tag}</div>".html_safe
}
```
```ruby
ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
html_tag.html_safe
end
```
Works instead.
2. Handling the date of birth …
> PID Collection

- azure/config/uat.parameters.json
This just adds a dedicated tracking id for prod (aka uat).
> Add google analytics tracking Id for prod environment

- app/controllers/users_controller.rb
- app/lib/url_parser.rb
- app/models/user_session.rb
- app/views/shared/_return_to_saved_results.html.erb
- app/views/shared/_save_your_results.html.erb
- spec/features/user_authentication_sidebar_spec.rb
- spec/features/user_sign_in_spec.rb
- spec/lib/url_parser_spec.rb
- spec/models/user_sessions_spec.rb
When a user adds an invalid email and is redirected back from the sign in
page, we should retain the email. We pass this as a query param in the redirect url.
Since `redirect_back` does not allow us to do this, build this functionality ourselves.
Also add an anchor to the email to make sure we scroll back down to the sign in form.
Move previous redirect logic to same URL Parser class as it shares the url is part of host
functionally.
> GET-412 Retain email on validation on sign in, and add anchor to url

- app/controllers/users_controller.rb
- app/lib/url_parser.rb
- spec/features/user_sign_in_spec.rb
- spec/lib/url_parser_spec.rb
To avoid having validation errors in other forms when submitting sign in
form, always overwrite params in url when there are validation errors
> Don't merge params when submitting sign in form

- azure/config/prod.parameters
This is adding the real Production environment parameters (on the prod subscription).
For the pen test will be using some QA configuration values to avoid contaminating the stats with not real traffic:
- GA Tracking ID will be the one from QA 
- Split.io will the the QA one so all the features are on.
- Gov Notify will also be the QA token.
*Actual Vault IDs pending.
> Add the production params 

- Dockerfile
- app/controllers/status_controller.rb
- app/services/health_check/check_base.rb
- app/services/health_check/courses_check.rb
- app/services/health_check/features_check.rb
- app/services/health_check/job_profiles_check.rb
- app/services/health_check/notify_check.rb
- app/services/health_check/postcodes_check.rb
- app/services/health_check/report_service.rb
- app/services/health_check/sessions_check.rb
- app/services/notify_service.rb
- azure-pipelines.yml
- config/application.rb
- config/features.rb
- config/routes.rb
- spec/requests/health_check_spec.rb
- spec/services/health_check/courses_check_spec.rb
- spec/services/health_check/features_check_spec.rb
- spec/services/health_check/job_profiles_check_spec.rb
- spec/services/health_check/notify_check_spec.rb
- spec/services/health_check/postcodes_check_spec.rb
- spec/services/health_check/report_service_spec.rb
- spec/services/health_check/sessions_check_spec.rb
- spec/services/notify_service_spec.rb
Health endpoint reports status of dependencies (Data and API endpoints) and meta data.
https://dfedigital.atlassian.net/browse/GET-340
This adds new Healthcheck service and check classes for key models and required integration points. The endpoint also includes select metadata - on Azure we'll need a pipeline change to populate `GIT_SHA` ENV var that can be read in `application.rb`.
This also adds a new health_check method to Notify service; that simulates sending a health check template to a smoke test email address. This exercises the Notify service without sending an actual email. If this fails a warn state is returned as we can still use the service otherwise.
For postcodes.io a geocoding call to a postcode is made - that should return lat/long, if not then a warn state is returned as …
> Add health check endpoint

- app/controllers/passwordless/sessions_controller.rb
- app/views/users/link_expired.html.erb
- app/views/users/return_to_saved_results.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/user_sign_in_spec.rb
- spec/routing/users_spec.rb
When the user has a token expired/claimed one
gets redirected to a link expired page.
From there one can request the link again.
https://dfedigital.atlassian.net/browse/GET-452
> Handle user token expired

- app/controllers/application_controller.rb
- app/services/tracking_service.rb
- config/application.rb
- config/initializers/application_insights.rb
- spec/features/check_your_skills_spec.rb
- spec/features/find_training_courses_spec.rb
- spec/features/location_eligibility_spec.rb
- spec/features/skills_builder_spec.rb
- spec/features/your_information_spec.rb
- spec/services/tracking_service_spec.rb
Refactor Azure Application Insights implementation to support better testing
This adds a new TrackingService class for custom event tracking so that we can set expectations on tracking data within associated feature specs. Moved AAI configuration to centralised Rails config object and cleaned up the existing initialiser code so that only the client side JS tracking and exception tracking are created on startup.
Custom tracking events lazily load Azure tracking telemetry client and cached at class level.
Also added feature specs for custom tracking to ensure this gets called with the correct payload.
This shouldn't affect any existing tracking, but just means we're able to add test coverage. I noticed whilst working on this that we don't have any custom event tracking for skills builder …
> Get 384 tracking refactor

- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/dev3.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
Following up the spike in https://dfedigital.atlassian.net/browse/GET-381 we decided to add a second database with different credentials to the infrastructure.   Since the credentials in azure database are managed at the server level and not the database level we had to create a new dedicated server.
This PR adds the necessary resources to the main ARM template to create this second database server, second logical database and reference the respective secrets from KeyVault
> GET-520 Add a second postgres database

- app/controllers/pages_controller.rb
- app/models/user_session.rb
- app/views/pages/task_list_items/_item_1.html.erb
- app/views/pages/task_list_items/_item_2.html.erb
- app/views/pages/task_list_items/_item_3.html.erb
- app/views/pages/task_list_items/_item_4.html.erb
- app/views/pages/task_list_items/_item_5.html.erb
- spec/features/task_list_spec.rb
- spec/models/user_sessions_spec.rb
The new flow is as follows:
1. When the user has no session, lands on task-list page
clicks on Check your existing skills, gets taken to search
for current job title form (check_your_skills path).
2. When the user selects a set of skills, which are persisted
already in the session by that time, all the sections on
task-list get unlocked. The user DOES NOT have to click on
Find what you can do next button anymore as per discussion with
Shelina & Lois.
3. If a user already has skills persisted on the session, when
landing to the task-list and clicking Check your skills link,
this will take the user to the skills summary page (skills_path).
This is compatible with bothe Skills Builder v1 & v2.
https://dfedigital.atlassian.net/browse/GET-417
We are aware that we are breaking the breadcrumbs …
> Alter locked sections user flow on task-list

- app/models/skills_matcher.rb
- spec/features/skills_matcher_spec.rb
- spec/models/skills_matcher_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-497
After grouping on skills match, order by growth, and then order alphabetically. I'd like to tackle the flakiness next in another ticket
Please find below a few examples of the ordering. I’ve uncovered the values for testing purposes:
First order through score:
Then through growth if the score is equal:
Then Alphabetically if the score and growth are equal:
Edgecase for growth being nil means it will appear at the top of the equal score group:
> GET-497 Order by growth then alphabetically on skills matching

- spec/services/tracking_service_spec.rb
Because this uses a class level instance variable, if the tests for tracking service run before other tests that make use of the tracking service, then the test output is polluted with warnings:
WARN -- application_insights: Failed to send data: Invalid instrumentation key
This doesn't cause tests to fail, but is a bit noisy. Explicitly clearing the key after the relevant test fixes this.
> Fix flaky test output for tracking service

- azure/template.json
The Slot Swap operation is a bit flaky. 
After going through the documentation and by experimentation we surfaced a few internal settings that seem to improve how this internal operation works. 
This PR adds a custom health-check endpoint which is more adequate to probe the healthiness of the application. And another setting aimed and improve the behaviour for Linux custom containers that do not interface with Azure the same way native .NET apps do.
> Add custom healthcheck and swap parameters

- app/models/skills_matcher.rb
When unnesting an aggregate array with ordinality with minimal syntax:
`WITH ORDINALITY ordered_id`, this was minimising the following
syntax:
`WITH ORDINALITY some_table(ids, ordinality_number)`
But this does not guarantee the order of the unnested arrays is maintained.
Explicitly ordering on the ordinality number as a secondary order
after the skills match makes sure the order is retained.
`
EDIT:
After some consideration realised we can tidy up this query and remove the unnecessary step of array aggregate ordering and un-nesting. This can be done with a normal `.order`
The following query should maintain the previous behaviour as well as eliminate the flakiness
jira-ticket: https://dfedigital.atlassian.net/browse/GET-407
> GET-407 Refactor query and tidy up because there is no need for complexity

- app/controllers/home_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/user_personal_data_controller.rb
- app/helpers/user_journey_helper.rb
- app/models/user_session.rb
- app/views/home/index.html.erb
- spec/features/home_spec.rb
- spec/features/location_eligibility_spec.rb
- spec/features/your_information_spec.rb
- spec/helpers/user_journey_helper_spec.rb
- spec/models/user_sessions_spec.rb
- spec/models/user_spec.rb
Skip PID/Postcode eligibility pages if the the information
has already been captured.
When user clicks start now:
a) if new session, go to postcode (eligibility) page
b) if user has a postcode (eligibility) but no personal
data in session, redirect to personal data page
c) if user has a postcode and personal data in session,
redirect to tasklist
When saving/returning to the journey, the same behaviour applies
for a user that has previously supplied the data.
https://dfedigital.atlassian.net/browse/GET-482
> Skip PID/Postcode Eligibility pages

- azure-pipelines.yml
This seems to be required by RVM: https://github.com/rvm/rvm/search?q=libncurses5-dev&unscoped_q=libncurses5-dev
> Add libncurses5-dev to azure pipeline

- Gemfile.lock
https://github.com/DFE-Digital/get-help-to-retrain/network/alert/Gemfile.lock/rubyzip/open
> Update rubyzip (dependency of roo) because of CVE

- app/models/skills_matcher.rb
- spec/models/skills_matcher_spec.rb
This still respects the original ordering, but limits results to 50.
* Add lots of common skills to skill builder
* Skill matcher results should return maximum 5 pages (50 job profiles)
> Restrict number of job profile matches to 50 maximum

- app/views/shared/search/_no_results.html.erb
No results page for job matches now includes an extra bullet point.
> Add extra bullet point for no results found page

- app/views/check_your_skills/_results_list.html.erb
- app/views/skills_matcher/_job_matches.html.erb
- app/webpacker/styles/_job-profile.scss
jira-ticket: https://dfedigital.atlassian.net/browse/GET-432
* Add a new screen reader hidden section to explain alternative jobs. There is
a discussion about using aria-label vs css solution but the css solution
is preferable. https://cloudfour.com/thinks/see-no-evil-hidden-content-and-accessibility/
I tried using `aria-label` and it puts the list into a group which is obscure
* For other changes required in the ticket, skills builder markup changed making it not an issue anymore, and the hidden text is not an issue after revisiting and discussing
> GET-432 Add Accessibility fixes

- app/views/layouts/application.html.erb
Address accessibility issues.
Header:
missing image description for Gov UK - addressed
breadcrumbs need navigation section indicator - addressed
breadcrumb groups confusing (always repeats on last element) - can't replicate
Footer: 
OGL unlabelled image - addressed
feedback form after selecting no not easy to navigate to - this will be changing when we update the in page survey anyway - not worth the effort as this is going away
General:
Skip to main content: includes beta banner and breadcrumbs, might skip to either breadcrumbs or actual content instead - investigate GDS or DAC guidance - addressed
> GET-440: Address accessibility issues

- app/helpers/application_helper.rb
- app/views/courses/_course.html.erb
- app/views/job_profiles/_highlights.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-441
For background images accessiblity there were quite a few implementations.
I went with the simpler one seen here: https://stackoverflow.com/questions/48913759/how-to-add-alt-text-to-background-images-making-background-images-accessible/#48913760
There is another approach with much more markup, having tested this, this seems adequate for now.
Also add hidden text to courses for providers 
Whilst we can't remove the extra list due to the clearfix class
being added by govuk frontend, we can point to the current page:
https://design-system.service.gov.uk/components/breadcrumbs/
We are adhering exactly to the rules of breadcrumbs seen there,
so Im going to keep it that way for now
> GET-441 Fix Job Profile page accessibility as well as courses and navigation

- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
Before going live we want to run our application in HA, so that we don't suffer an outage if one instance of application dies due to a crash or other instance specific isshue. 
This PR passes a parameter that overrides the default number of instances of 1.
This parameter overrides the default defined in the generic templates.
https://github.com/DFE-Digital/get-help-to-retrain-devops/blob/master/templates/app-service-plan.json#L32-L35
> GET-561 Run two instances in QA, UAT, PROD

- lib/tasks/data_import/update_recommended_job_profiles.rake
Update list of recommended job profiles. See https://dfedigital.atlassian.net/browse/GET-408
Also sorted list of slugs into alphabetical order to make it easier to track future changes to this list.
Run rake task `rails data_import:update_recommended_job_profiles` - note that I've not run that on the heroku review app. The list of job profiles that need a degree is hardcoded, so doesn't need a spreadsheet to test locally.
> Added extra non recommended job profiles to rake task

- app/models/user_session.rb
- spec/features/user_sign_in_spec.rb
- spec/support/session_helper.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-538
When users were hitting the page for the first time we were deleting
the session from the database as they didn't have a version in the data.
This was causing unnecessary read/write to the database also causing the
database to seem like it was "skipping" ids, which were records created and
deleted unnecessarily.
This also caused an issue with authenticated users linked to sessions. If a user was signed
in with a session and the version changed, which caused their session to be deleted they could
not log in again, but rather see an error where we were trying to access a non existing session.
Now we "clear" the session instead of deleting it, only if the session has data, meaning there are no
unnecessary writes to the db, and we …
> GET-538 Do not destroy session if versions are different

- azure-pipelines-deploy-template.yml
- azure-pipelines.yml
Refractor deployment into a template for re-use
This PR just moves the deployment logic into a template, so that it DRYs the deployment to multiple environments when needed. 
Some code cleaning before adding the test stages.
> Refractor deployment into a template for re-use

- app/views/pages/cookies_policy.html.erb
- app/views/pages/privacy_policy.html.erb
* note: in the `mail_to` helper it needs the content before the class
* *For the future we should look into moving this rule to all links, unless there are any exceptions*
> Add links styling to privacy policy

- app/services/health_check/find_a_job_check.rb
- spec/services/health_check/find_a_job_check_spec.rb
In Sentry we are getting different errors from the DWP API like socket errors
and read timeouts. We were initially only rescuing from bad responses from the API
but we should also account for those, so now we rescue from Standard error instead
> Rescue from standard error rather than response errors

- app/helpers/application_helper.rb
- app/models/user_session.rb
- spec/helpers/application_helper_spec.rb
- spec/models/user_session_spec.rb
We have a few stories that depend on having a 'target job profile' being selected.
This PR simply adds a new key for `target_job_id` to the `UserSession` and a helper method that will return either the relevant `JobProfile` instance or nil; this can be used as needed in various controllers.
Also renamed user_sessions_spec to have correct name.
> Add support for target job in user session

- azure/config/uat.parameters.json
The UAT environment was being used as the live environment until Phase3 so it was under the beta.nrs-ghtr.org.uk FQDN.
This PR changes this back to uat.nrs-ghtr.org.uk
> Reset UAT environnet customHostname to uat.

- app/views/skills/index.html.erb
- spec/features/skills_builder_spec.rb
User can only see the following breadcrumbs items:
Home: Get help to retrain
Your skills
https://dfedigital.atlassian.net/browse/GET-531
> Simplify breadcrumbs on Your Skills page

- app/views/courses/index.html.erb
- spec/features/find_training_courses_spec.rb
https://dfedigital.atlassian.net/browse/GET-618
This only applies when the action plan feature is enabled - the breadcrumb trail links back to the action plan rather than the training hub. Also the sidebar partial for next steps is hidden as the next steps page will ultimately be completely replaced by the action plan.
The updated breadcrumbs are slightly repetitive but this approach makes it simpler to remove the legacy behaviour once the feature is promoted, so I didn't attempt to DRY things up at this stage. Added some basic feature level coverage to accompany change.
Only affects courses page - see `/courses/maths` and `/courses/english` - needs to be tested both with and without `action_plan` feature enabled.
> Amend breadcrumb and sidebar content for courses page

- app/controllers/home_controller.rb
- app/views/home/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_return_to_saved_results.html.erb
- app/views/shared/_save_or_return_to_your_results.html.erb
- spec/features/home_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-490
Sessions are lazy loaded. If we don't touch teh session on
the homepage we can avoid creating it unnecessarily.
The three places the session is created and avoided are:
1) csrf token: skip this tag if its the homepage
2) start link: render the information page if the cookie
is missing. The cookie is created when we have a session.
Default to normal behaviour if the cookie exists
3) authentication partial: default to return to saved results
unless there is a cookie, where then we default to previous
behaviour
> GET-490 Avoid session creation on homepage

- app/views/check_your_skills/results.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-652
We should always start with H1 and move down when defining titles/subtitles
> GET-652 Add h1 to current jobs results page to follow DAC regulations

- app/views/user_personal_data/_form.html.erb
DAC suggested the following fixes:
1. Add a fieldset/legend for date of birth
2. Add a fieldset/legend for gender
Resources
https://design-system.service.gov.uk/components/date-input/
`field_set_tag :name` will create a markup like this:
```ruby
<%= field_set_tag do %>
<p><%= text_field_tag 'name' %></p>
<% end %>
<%= field_set_tag 'Your details' do %>
<p><%= text_field_tag 'name' %></p>
<% end %>
```
However, we want a different nesting as per GDS design system e.g:
```ruby
<div class="govuk-form-group">
<fieldset class="govuk-fieldset" role="group" aria-describedby="passport-issued-hint">
<legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
<h1 class="govuk-fieldset__heading">
When was your passport issued?
</h1>
</legend>
<span id="passport-issued-hint" …
```
> Get 650 fieldset legend dob gender

- app/views/courses/_course.html.erb
- config/brakeman.ignore
jira-ticket: https://dfedigital.atlassian.net/browse/GET-654
The link on the courses search page has many visit page buttons,
add aria label to describe where the link is going to be DAC
compliant
> GET-654 Add aria label to courses visit page button

- app/views/users/return_to_saved_results.html.erb
Return to saved results page should have more
context around Send Link button and what it does.
https://dfedigital.atlassian.net/browse/GET-657
> Add context for Send Link button

- app/views/courses/index.html.erb
- app/views/job_vacancies/index.html.erb
- app/views/user_personal_data/_form.html.erb
- app/views/users/new.html.erb
- app/views/users/return_to_saved_results.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-656
To coform to WCAG guidelines add autcomplete attribute to all inputs
in forms.
The value of attributes has been taken from:
https://www.w3.org/TR/html52/sec-forms.html#sec-autofill
with a table explaining the what the expected values map to
Other good links include:
https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html
and the gov uk example:
https://design-system.service.gov.uk/components/text-input/
> GET-656 Add autocomplete to all forms across app

- app/views/skills_matcher/_job_matches.html.erb
- app/views/skills_matcher/index.html.erb
- app/webpacker/styles/_job-profile.scss
- config/locales/en.yml
- spec/features/skills_matcher_spec.rb
Update paragraph 1 and 2
Remove salary
Update link label change text
Update the job growth details
Use the propper GDS accordion component
Update the font size for Skills match, Recent job growth:
Fix DAC accessibility fail Non-descriptive buttons/details component
issue (page 31 on the report) by updating aria label.
James Cutt from a team using the same Details component has shwon a nice
solution:
```ruby
<details class="govuk-details" role="group" open="">
<summary class="govuk-details__summary" aria-controls="details-content-92" aria-expanded="true" role="button" tabindex="0">
<span class="govuk-details__summary-text" data-testid="Expand Details Section Download data files">Download data files</span>
</summary>
<div class="govuk-details__text" aria-hidden="false" …
```
> Content updates to jobs matches page

- app/controllers/courses_controller.rb
- app/controllers/job_vacancies_controller.rb
- app/views/courses/index.html.erb
- app/views/job_vacancies/index.html.erb
- spec/features/find_training_courses_spec.rb
- spec/features/jobs_near_me_spec.rb
https://dfedigital.atlassian.net/browse/GET-683
* Hide postcode params in pagination by setting it to nil on both pages
* Update postcode in session on both pages if user updates it in the form
> GET-683 Hide postcode in pagination and update Postcodes in Jobs near me and Courses page

- app/views/pages/action_plan.html.erb
- app/webpacker/styles/_action-plan.scss
- spec/features/action_plan_spec.rb
This PR introduces the following changes:
Amendment of 1st paragrapg (type of work)
Target job: change the word ‘job’ to ‘type of work’ throughout this section
Your skills section: 2nd para change ‘You can see different types of work ideas if you edit your skills.’
CV section: change heading to ‘Get ready to change types of work’
Apply for a job section: change link to ‘Change target types of work’
as per prototype
https://get-help-to-retrain-prototype.herokuapp.com/main/release4_e2e_v2/action_plan?task-2=complete
> Content updates for Action Plan section

- spec/features/find_training_courses_spec.rb
Replicate test failure using:
`be rspec ./spec/features/find_training_courses_spec.rb[1:8,1:9,1:13] --seed 33797`
Postcode is seen as not real if no geocode is defined for it and thus will be invalid
and not saved into the session. Make sure to define it's geocoding to make sure it's valid.
> Fix flakey courses test

- app/views/skills/_job_profiles_with_skills.html.erb
- app/views/skills/index.html.erb
- app/webpacker/styles/_skills-builder.scss
- spec/features/skills_builder_spec.rb
- spec/features/user_sign_in_spec.rb
- spec/features/user_sign_in_through_registration_spec.rb
https://dfedigital.atlassian.net/browse/GET-649
Now instead of listing individual skills, summarises as "3 skills selected" for each job profile. This is less repetitive for screen readers. Cleaned up existing markup slightly and removed redundant styles. Updated feature specs to reflect.
I left out the centre align styles from the prototype markup - this looks really weird at narrow device widths. As a result the links to 'edit' and 'remove' are not in quite the same horizontal position as the prototype but responsiveness is improved.
> Amendments to skills builder page

- .gitignore
- app/controllers/job_profiles_controller.rb
- app/controllers/job_vacancies_controller.rb
- app/services/find_a_job_service.rb
- app/services/health_check/find_a_job_check.rb
- app/views/errors/jobs_near_me_error.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/job_profile_spec.rb
- spec/features/jobs_near_me_spec.rb
- spec/routing/action_plan_spec.rb
- spec/services/find_a_job_service_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-621
The errors for find a job service were a bit of a mess, so now made them
consistent to the following:
1) If there is an internal API response error we raise a Response Error
which we catch and for outside services this is seen as an API error
2) If there is a NET::HTTP error, the best way is to save it through standard
error see: https://stackoverflow.com/questions/5370697/what-s-the-best-way-to-handle-exceptions-from-nethttp
rescue that and raise also API error for outside services. Since we are
now doing that in the find a job service itself, remove the need to
do that from the healthcheck service and rescue from API error instead
3) For job vacancies on the search page, show error page and rescue from
new API error
4) For job …
> GET-621 Show error page if Find a Job API is down and cleanup exceptions for service

- app/webpacker/packs/track-events.js
Fix IE11 compatibility issue
We currently have for event tracking that is using
forEach function. However, IE11 throws the following
error:
Object doesn't support property or method 'forEach'
Because of this the behaviour our accordion component
is broken on IE11 giving bad user experience.
Decided to go with the simplest solution of using the
classic for loop.
Please use: https://dev1.nrs-ghtr.org.uk/task-list
And browserling.com
> GET-682: Fix IE11 compatibility issue 

- app/scrapers/job_profile_scraper.rb
- lib/tasks/data_import/refresh_job_profiles.rake
Well, actually it turns out that the Wombat gem makes use of class level instance variables, and writing directly to the `metadata` class causes pollution across other instances of the same `Crawler` class. `JobProfileScraper` derives from this class:
```ruby
module Wombat
module Crawler
include Processing::Parser
extend ActiveSupport::Concern
included do
class << self
attr_accessor :metadata
end
self.metadata = DSL::Metadata.new
end
```
The fix for this took a while to resolve, (tried many approaches) but turns out to just require clearing the parsed page (setting it to `nil`) which forces the next scraped page to be parsed correctly. This is the magic line:
```ruby
metadata[:page] = nil
```
Also took the opportunity to clean up the rake task implementation by offloading some of the …
> Fix flaky specs caused by strange quantum tunnelling effect

- app/controllers/users_controller.rb
- app/services/notify_service.rb
- app/views/errors/return_to_saved_results_error.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/user_sign_in_spec.rb
- spec/services/notify_service_spec.rb
Add a Return to results: Error page
when notify fails to send magic link email
https://dfedigital.atlassian.net/browse/GET-496
Try altering the API key on HEROKU to get to this page naturally.
> Inform users if the Notify Service is not working

- app/controllers/errors_controller.rb
- app/controllers/users_controller.rb
- app/views/errors/save_results_error.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/user_registration_spec.rb
If notify service is down, users will get an error
page explaining what is happening.
Users can still resume their journey.
1. Please check you can resume the journey (try saving results at different stages)
2. Deeplinking to the error page should redirect to task-list page.
https://dfedigital.atlassian.net/browse/GET-526
> Add service error page for user registration

- azure/config/qa.parameters.json
We introduced a temporary domain database in the qa environment to respond to a MS Azure service failure.  We don't need it anymore
This reverts to the original database instance.
> Revert the temporaty database in qa

- app/services/health_check/check_base.rb
- app/services/health_check/features_check.rb
- app/services/health_check/find_a_job_check.rb
- app/services/health_check/notify_check.rb
- app/services/health_check/postcodes_check.rb
- app/services/health_check/report_service.rb
- spec/requests/health_check_spec.rb
We are currently caching details, but not the status, which makes internal calls to all endpoints again. Cache the status as well.
Also if an API is down, we are not memoizing the method result `value` as we are rescuing from exceptions, this causes the API to be called multiple times every time we invoke the method `value`. Change that so we only call it once
> Fix caching in Health status endpoint

- app/webpacker/packs/application.js
- app/webpacker/packs/outbound-link-tracking.js
jira-ticket: https://dfedigital.atlassian.net/browse/GET-661
We need to track clicks that send users to outbound urls, either through
the same window or through the a new tab. Add JS which does the following
taken from:
http://www.joehessert.com/seo/google-analytics-external-link-tracking
https://support.google.com/analytics/answer/7478520?hl=en
1) gets all links (our buttons that link to outside are just button styled
links)
2) check the domain, and make sure its not a mailto/call link
3) Get the url target (same tab/different tab)
4) Log the click if its an outbound url using gtag event
Testing:
Use the heroku app to navigate to outside urls and look for events on realtime 
Tested on IE11 and seems reasonably ok, will confirm with Mak after his crossbrowser testing …
> GET-661 Enable GA tracking for outbound urls

- app/views/check_your_skills/_results_list.html.erb
- app/views/check_your_skills/_search_form.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/search/_results_form.html.erb
- app/webpacker/styles/_job-profile.scss
- config/locales/en.yml
- spec/features/check_your_skills_spec.rb
1. All job results titles are underlined now
2. New subtitle paragraph
3. When a user has already input a job, when adding new ones
one should see Your previous job title on results page
4. Remove job-search-form-group-tag tag class from the form as
it doesn't seem to be needed anymore.
https://dfedigital.atlassian.net/browse/GET-642
> Update content as follows:

- app/controllers/job_profiles_controller.rb
- app/controllers/job_profiles_skills_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/skills_controller.rb
- app/views/job_profiles/skills/index.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/search/_results_form.html.erb
- app/views/users/new.html.erb
- app/views/users/return_to_saved_results.html.erb
- spec/features/skills_builder_spec.rb
- spec/features/task_list_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-637
* If there are no skills stay on page
* If there is no params remain on page
* Cleanup params for search/job profile id as they are no longer required for breadcrumbs or page logic
* Cleanup button params
> GET-637 Do not redirect from skills page when no skills available, also params cleanup

- app/views/courses/_course.html.erb
- app/views/courses/index.html.erb
- app/views/home/index.html.erb
- app/views/job_vacancies/_job_vacancy.html.erb
- app/views/job_vacancies/index.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/cookies_policy.html.erb
- app/views/pages/location_ineligible.html.erb
- app/views/pages/privacy_policy.html.erb
- app/views/pages/task_list_items/_item_4.html.erb
- app/views/shared/_help_improve_this_service.html.erb
- config/brakeman.ignore
- spec/features/task_list_spec.rb
- spec/helpers/task_list_helper_spec.rb
Now that we have these links tracked in GA, we can drop
the tracked-event data attribute as we don't need to track
them in AppInsights.
NOTE:
We can not yet get rid of TrackEvents() JS function as
we still need to track the interraction on our inpage
smart survey(`shared/feedback/_survey.html.erb`) Once we implement GA backend tracking,
we can drop this script.
Set GOOGLE_ANALYTICS_TRACKING_ID to the workspace you want to use (I used QA) and see the outbound events coming though in real-time.
> All outbound links open in the same tab

- app/views/job_profiles/skills/index.html.erb
Use types of work instead of types of job on Skills Builder page.
https://dfedigital.atlassian.net/browse/GET-644
> Update content for skills builder

- app/views/courses/_course.html.erb
- app/webpacker/styles/_course.scss
- app/webpacker/styles/application.scss
https://dfedigital.atlassian.net/browse/GET-703
Tweaked styles, removed redundant stylesheet for courses as it's now empty - removed class is not used elsewhere.
Just check english and maths course results page.
> Update styling for course titles/subtitle

- app/controllers/job_profiles_controller.rb
- app/views/job_profiles/_skills_section.html.erb
- spec/features/job_profile_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-728
* Add existing skills by checking intersection with user session
* Add missing skills by diffing user session with job profile skills
* Only show section if there are any skills available
> GET-728 Add skills gap section to Job profiles

- app/views/skills_matcher/_no_results.html.erb
- app/views/skills_matcher/index.html.erb
- spec/features/skills_matcher_spec.rb
https://dfedigital.atlassian.net/browse/GET-747
The no results page now intentionally keeps the existing title and intro paragraph, plus the link to search for a specific job title regardless of skills match results appearing or not.
Try using this test scenario: `be a religious leader and only tick ‘knowledge of philosophy and religion’`
> Update copy and UX for "no matches" in skills matcher

- app/decorators/job_profile_decorator.rb
- app/views/job_profiles/_apprenticeship.html.erb
- app/views/job_profiles/_highlights.html.erb
- app/views/job_profiles/_relevant_sections.html.erb
- app/webpacker/styles/_job-profile.scss
- spec/decorators/job_profile_decorator_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-769
* Add expected/experienced to salary range. This required adding three custom columns for responsiveness as it wouldn't work with normal columns from the govuk styles, which collapsed and overlapped in strange ways. 
* Amend apprenticeships content
* Amend target job section
* Add new link to bottom of page to go back to job matches
> GET-769 job profile content tweaks

- app/decorators/job_vacancy_decorator.rb
- app/models/job_vacancy.rb
- app/views/job_vacancies/_job_vacancy.html.erb
- app/views/job_vacancies/index.html.erb
- spec/decorators/job_vacancy_decorator_spec.rb
- spec/models/job_vacancy_spec.rb
https://dfedigital.atlassian.net/browse/GET-707
It's not possible to include distance to each vacancy as that info is not included in the DWP FAJ API response - we only pass a partial postcode so even if the API performed a spatial calculation it would not be accurate. Refactored date formatting slightly to DRY things up.
The intro text on the prototype is out of date - double checked with Lois and it's only the extra sentence about going to another site that needed to be added.
> Add closing date and copy changes for job vacancies

- app/views/job_profiles/skills/index.html.erb
First paragraph size on Skills Builder page same size as the following ones.
> GET-768 First paragraph same size as the following ones

- app/views/job_profiles/_jobs_in_your_area.html.erb
- config/locales/en.yml
- spec/features/job_profile_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-720
is/are does not work with normal pluralisation so had to add it in the local to use it see https://guides.rubyonrails.org/i18n.html#pluralization
> GET-720 Add plularisation for is/are and fix content on job vacancies

- app/controllers/application_controller.rb
- app/controllers/job_profiles_skills_controller.rb
- app/controllers/questions_controller.rb
- app/helpers/ga_tracking_helper.rb
- app/services/tracking_service.rb
- config/locales/en.yml
- spec/features/check_your_skills_spec.rb
- spec/features/find_training_courses_spec.rb
- spec/features/questions_spec.rb
- spec/features/skills_builder_spec.rb
- spec/features/your_information_spec.rb
- spec/helpers/ga_tracking_helper_spec.rb
- spec/services/tracking_service_spec.rb
Switch to GA server side tracking for user events
1) Replace AppInsights server side tracking with GA
server side tracking
2) Allow batch requests sending
3) Tracked sections:
- skills search
- postcode search
- courses search
- skills builder
- training questions
- job_hunting questions
Decided to go with the following approach:
```ruby
track_events(:key, props), where props is an array of props defined by a (label, value) pair.
```
I do think it's really intuitive from a usage perspective. Can't think of a better way of doing it.
https://dfedigital.atlassian.net/browse/GET-794
> Add batch processing to the TrackingService

- package.json
- yarn.lock
Since this is a sub dependency it seems we have to define it as a resolution:
https://yarnpkg.com/lang/en/docs/selective-version-resolutions/
https://til.hashrocket.com/posts/unsfxg7dmw-force-upgrade-of-transitive-dependencies-in-yarn
> Update serialize javascript package

- app/models/course_geospatial_search.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-738
Cache API calls using the postcode as the key. Instead of attempting
to save coordinates in the session, use low level caching for the
coordinates API lookup. We set it to an hour as that seems enough
for users paginating through their results
The reason I avoided saving it in the session are the following:
1) We do not use geocoding everywhere, meaning if we change the
postcode in find a job we will need to update the coordinates.
Forcing us to do an API call when we don't need it, meaning
we might throw an error unnecessarily
2) Attempting to pass in the user session and update the coordinates
only if they changed also didn't work as sometimes we set the postcode
on the session even if it doesn't exist (PID form). This also …
> GET-738 Low level caching for geocoding

- app/controllers/skills_matcher_controller.rb
- app/models/skills_matcher.rb
- app/models/user_session.rb
- app/views/skills_matcher/_sort_form.html.erb
- app/views/skills_matcher/index.html.erb
- app/webpacker/packs/application.js
- app/webpacker/packs/sorting.js
- spec/features/skills_matcher_spec.rb
- spec/models/skills_matcher_spec.rb
- spec/models/user_session_spec.rb
https://dfedigital.atlassian.net/browse/GET-775
Preferred sort order is stored in the user session to avoid having to pass this around as a parameter. Added support for another option to specify order in the skills matcher (we only need this for the main list of skill matches, not when searching for a job profile by name - but this could easily be added later if needed).
Add some skills, show match results and experiment with sort order. It's pretty hard to tell the order has changed unless the skills are chosen wisely, but the correct query can be observed in the console.
> Add support for sorting skill matcher results

- config/environments/production.rb
We set static cache-control to 'public, max-age=31536000'
so the browser caches all static assets for up to a year.
In production, every asset has a hash added to its name,
so whenever the file changes the browser requests
the latest version as the hash and therefore the whole
filename changes.
> Cache all static assets

- azure/config/qa.parameters.json
This sets the QA Webapp hostname to qa-origin, so that it can be fronted by Azure FrontDoor
> Rename QA to qa-origin so that it can be fronted by Azure FrontDoor

- app/controllers/job_profiles_controller.rb
- spec/features/skills_matcher_spec.rb
pass in the value without a hash, as this is now appearing as `{'search' => 'some value'}` in google analytics
> HOTFIX - google analytics job profile search

- package.json
- yarn.lock
Upgrade dependencies to fix the `serialize-javascript` problem. I attempted to upgrade to Node version 12 but the alpine version we are using has only `10.x.x` node package versions. Edge is the only one that has 12 right now.
**tested full journey locally, on heroku and Dev1** with also with GA
> Upgrade Node dependencies

- app/admin/dashboard.rb
- app/admin/user_personal_data.rb
- app/models/user_personal_data.rb
https://dfedigital.atlassian.net/browse/GET-815
Needed to tweak validation for `UserPersonalData` slightly to allow ActiveAdmin to edit the `dob` field directly. Other than that this just adds a new Admin class and includes a link on the dashboard. 
Worked with Lois to iron out the columns, filters etc. for this and is happy. Will need to add support for the `ADMIN_MODE` flag to get this deployed on a review app, so will cover that in the next story. For now this is still only exposed in development mode so will need to be tested locally.
> Add support for viewing and editing user personal data via active admin

- app/views/courses/_course.html.erb
- app/webpacker/packs/outbound-link-tracking.js
- config/brakeman.ignore
When users click on different course providers,
we want to track which topic these course
providers fall under.
https://dfedigital.atlassian.net/browse/GET-846
> Customize event category for outbound links

- Gemfile
- app/constraints/admin_constraint.rb
- app/constraints/user_constraint.rb
- config/application.rb
- config/locales/en.yml
- config/routes.rb
- spec/routing/admin_spec.rb
https://dfedigital.atlassian.net/browse/GET-804
If this variable is set then only the ActiveAdmin routes are exposed (not yet authenticated). If not set then only the user facing routes are exposed. I left the Feature flag UI out of this for now as we might want to use that in either mode, and it's only available for local development.
With admin mode on, site root directs to the admin pages and no customer facing routes are available. With the admin mode flag off the site behaves in customer facing mode only, no admin routes are available.
Routes are not evaluated dynamically so the proposed `if / then / else` approach didn't work. Adding custom constraint classes proved to be a nice solution though. The diff is a little messy but essentially this just adds a `constraints` block around …
> Add support for `ADMIN_MODE` environment variable

- app/services/health_check/check_base.rb
- app/services/health_check/find_a_job_check.rb
- app/services/health_check/notify_check.rb
- app/services/health_check/postcodes_check.rb
- app/services/health_check/report_service.rb
- app/services/health_check/sessions_check.rb
- spec/services/health_check/find_a_job_check_spec.rb
- spec/services/health_check/notify_check_spec.rb
- spec/services/health_check/postcodes_check_spec.rb
- spec/services/health_check/sessions_check_spec.rb
https://dfedigital.atlassian.net/browse/GET-855
We don't need to connect to external services, and will not be using database backed sessions for admin mode, so it doesn't make sense to have these enabled in the reporting service when the site is in admin mode. This should fix the slot swapping when deploying admin mode site on Azure.
Set `ADMIN_MODE=true` and then examine results of `/status` endpoint. I'll set that environment variable on heroku review app once this has been deployed.
> Disable irrelevant health checks in admin mode

- app/views/courses/_course.html.erb
- config/brakeman.ignore
For courses, use a better event category name when
tracking the outbound links.
> Improve event category outbound links

- Dockerfile
https://dfedigital.atlassian.net/browse/GET-856
This is a temporary measure until ActiveAdmin adds support for Webpacker. There is an ongoing PR to add Webpacker support to ActiveAdmin in a future release, but we can't depend on this being released soon. In the meantime, using `assets:precompile` step rather than `webpacker:compile` combines both the sprockets based pipeline to generate the ActiveAdmin related assets and webpacker compilation for the main application CSS and Javascript packs.
Deployed to Dev1, with `ADMIN_MODE` flag on, and it's all working nicely.
> Generate ActiveAdmin assets for deployment v2

- lib/tasks/data_import/update_recommended_job_profiles.rake
https://dfedigital.atlassian.net/browse/GET-862
Once we have growth data for these then the list can be updated; the data for these has been manually changed already but it's good to keep the rake task in sync just in case someone runs this accidentally in future.
Run the rake task - will need to have the new job profiles scraped already.
> Adds all of the newly scraped job profiles to the list of non-recommended jobs

- README.md
- app/admin/skills.rb
- app/models/job_profile_skill.rb
- app/models/skills_matcher.rb
- db/migrate/20191217141306_add_rarity_to_skills.rb
- db/schema.rb
- lib/tasks/data_import/update_skills_rarity.rake
- spec/models/job_profile_skill_spec.rb
- spec/models/skills_matcher_spec.rb
- spec/tasks/update_skills_rarity_spec.rb
https://dfedigital.atlassian.net/browse/GET-746
Adds a new `rarity` attribute to `Skill` model. This is precalculated via a new rake task and represents the frequency of each skill by ranking them. The lowest rank of `1` represents unique skills, higher numbers represent more commonplace skills.
When job profiles have identical growth and number of skills matched, then the skills rarity is used to further prioritise matches. This requires updating the skills matcher to also join against skills table to determine appropriate rarity for each skill. However, In order to avoid returning duplicate job profile results the query returns only the lowest rarity of all skills matched to a job profile (i.e. the rarest).
Also added new rarity attribute to admin interface and added appropriate test …
> Get 746 skills rarity

- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
Removing the Bing key from the specific ENV templates will allow it to be optional. This has been tested on Dev1
> Remove Bing key from ENV templates to allow it to be optional

- app/helpers/action_plan_helper.rb
- app/views/pages/action_plan.html.erb
- spec/features/action_plan_spec.rb
- spec/helpers/action_plan_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-844
User should be able to navigate to the apprenticeship search page
with their target job, outcode (if available) and distance of 20 miles.
If a user does not have a postcode show an empty search prompting them
for a postcode.
Note that the params in the url were trimmed down to the bare minimum needed without disrupting the search results themselves (see original url in ticket)
> GET-844 Build specific apprenticeship link for action plan

- azure-pipelines-deploy-template.yml
The default succeeded() condition was overwritten by our non-equals "disabled" rule.   
This fix includes the succeeded() condition explicitly
> Do not override succeeded() condition on admin webapp swap

- azure/config/prod.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
These environments are not enabled, so this config should be removed to avoid referencing non-existent secrets in vault
> Remove admin auth config from non-enabled environments

- app/controllers/application_controller.rb
- app/helpers/ga_tracking_helper.rb
- app/services/tracking_service.rb
- spec/services/tracking_service_spec.rb
To fix the inflated stats on users when sending custom
events and also the reported location we need to enrich
the payload we send as follows:
- cid will gold the _ga cookie value (as unique identifier)
- uip will hold the client's IP
- ua will hold the user agent information
https://dfedigital.atlassian.net/browse/GET-879
> Fix inflated users stats and location in GA

- app/decorators/job_profile_decorator.rb
- app/models/skills_matcher.rb
- app/views/job_profiles/_job_profile.html.erb
- lib/tasks/data_import/update_recommended_job_profiles.rake
- spec/decorators/job_profile_decorator_spec.rb
- spec/features/skills_matcher_spec.rb
- spec/models/skills_matcher_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-828
Use custom ordering for growth embed in other sorting orders. This
specifies that growth nil should come last, but maintains growth in
decsending order.
https://stackoverflow.com/questions/5826210/rails-order-with-nulls-last
Also add `No data available` on nil growth job profiles.
Regarding non recommended jobs, I've run the rake task on heroku, but we need to do this on azure and copy data when this is in qa
> GET-828 Growth nil job profiles should appear in the end rather than beginning

- app/views/shared/_cookies_banner.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-860
* Change main to div in banner to avoid duplicate main section
* Change role to region as that seems to be appropriate as seen
in: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Region_role
and on https://www.gov.uk/
tested by pointing smoke tests to localhost and not seeing failure anymore
> GET-860 Remove duplicate main section from cookies banner

- app/models/admin_user.rb
When logging in  an update event is triggered:
The provided value is not that significant and it could easily become just noisy and also a bit confusing.
> Remove AdminUser tracking as it is too noisy

- azure/template.json
https://dfedigital.atlassian.net/browse/GET-873
The parameter object for the tags was being passed into the wrong place on the ARM template structure for a particular resource.  This is a fix for that "bug"
> Fix bad location of tags parameter on admin webapp resource

- app/views/layouts/application.html.erb
- app/views/shared/_cookies_banner.html.erb
- app/webpacker/packs/cookies-banner.js
jira-ticket: https://dfedigital.atlassian.net/browse/GET-859
* Remove duplicate header from cookie banner partial
* Use js to move header div inside fixed div when cookie banner is visible
and move it back out when done. If cookie banner is not visible, it will
appear as normal.
I've played around with this and another option would be to add a div around
both cookies and header and fix that, but this seemed like the least obtrusive way.
> GET-859 Remove duplicate banner landmark

- app/webpacker/packs/cookies-banner.js
Prevent users from tabbing anywhere outside the cookies
modal when this is visible.
Inspired from: https://stackoverflow.com/questions/32996817/vanilla-javascript-trap-focus-in-modal-accessibility-tabbing
And other similar resources.
https://dfedigital.atlassian.net/browse/GET-843
> Trap focus inside cookies modal

- app/views/user_personal_data/_form.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-872
Radio buttons don't support autocomplete, remove it as per the DAC report
and axe tests
DAC report page 23: https://drive.google.com/drive/u/1/folders/1NaXsVGnJrxot_RwAVGVklY_LIXRMnlcE
Testing:
Run smoke test and check user personal data page does not have this failure: autocomplete valid on 3 nodes
> GET-872 Remove autocomplete from radio buttons

- app/views/layouts/application.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-861
Feeback div was outside the main landmarks:
https://dequeuniversity.com/rules/axe/3.3/region?application=axeAPI
Move it into main div, and fix styling so it's exactly like it was before
(move bottom padding to last div instead of main)
This also works the same with javascript disabled.
I've had a look at many gov websites and how they implement this
including https://www.gov.uk/, and all have feedback outside main,
and not in the footer (which I've considered). They however do fail the
axe test. I also had a look at roles and if we could add a role to this
feedback block but nothing felt like it fit.
Testing:
1) Test with smoke tests and should not see this error: region on 1 node
2) Test with disabling javascript to have the …
> GET-861 Move feedback to inside main landmark

- app/views/check_your_skills/_results_list.html.erb
- app/views/job_profiles/_highlights.html.erb
- app/views/job_profiles/_job_profile.html.erb
- app/views/user_personal_data/_form.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-874
* Fix order of headings on user personal information page
* Fix order of headings on skills matcher as well as check your skills
results pages. This causes the text to be slightly bigger
* Fix order of headings on job profile page
Testing:
1) User personal information page there should be no change in size
2) Skills matcher/check your skills very slight change in size will run past steve tomorrow
3) Profile page no change in size (brief section: typical salary and recent growth)
failure to look for in AXE: `11Y ERROR! heading-order on 1 Node`
`Description:  Ensures the order of headings is semantically correct`
> GET-874 Fix order of headings

- app/views/shared/feedback/_survey.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-876
An input element with type submit should include the aria-label
as seen from: https://dequeuniversity.com/rules/axe/3.1/button-name?application=lighthouse
We do not need a labeled by as the label is hidden and on the button itself.
Testing:
Run smoke test and the following error should disappear from all pages:
```
A11Y ERROR!
button-name on 1 Node
Ensures buttons have discernible text
```
> GET-876 Add missing aria label to submit tag in feedback

- app/lib/omni_auth/strategies/azure_ad_auth.rb
We want to build the redirect_uri in Omniauth ideally dynamically by parsing the requests at the rack level.
Check: https://github.com/omniauth/omniauth/blob/c2380ae848ce4e0e39b4bb94c5b8e3fd0a544825/lib/omniauth/strategy.rb to understand how that's done.
omniauth/omniauth-oauth2#93
https://docs.microsoft.com/en-us/graph/tutorials/ruby?tutorial-step=3
We also leave the option to explicitly set the `redirect_uri` as options.
This will allow us to have multiple callback urls setup in Azure AD.
> Allow multiple callbacks rack

- app/admin/paper_trail_versions.rb
- app/admin/user_personal_data.rb
- app/helpers/admin/authentication_helper.rb
- spec/features/admin/auditing_spec.rb
Re-using the object changes field, and
capture the search query and results count while on
PID on auditing.
Useful resource for retrieving the full filtered collection (not just first page of results): https://stackoverflow.com/questions/26215985/activeadmin-access-filtered-collection
https://dfedigital.atlassian.net/browse/GET-878
> Audit searches on PID

- app/helpers/question_helper.rb
- app/views/questions/it_training.html.erb
- app/views/questions/job_hunting.html.erb
- app/views/questions/training.html.erb
- spec/features/questions_spec.rb
- spec/helpers/question_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-897
* Add indicator on all question pages up to 3
* Indicator should not appear on page if already seen example when editing
from the action plan page
* If user interrups their question journey, they should see the indicator
> GET-897 Add progress indicator on question pages

- app/decorators/job_profile_decorator.rb
- app/views/job_profiles/_apply_to_become.html.erb
- app/views/job_profiles/_apprenticeship.html.erb
- app/views/job_profiles/_jobs_in_your_area.html.erb
- app/views/job_profiles/_relevant_sections.html.erb
- app/views/job_profiles/_skills_section.html.erb
- spec/decorators/job_profile_decorator_spec.rb
- spec/features/job_profile_spec.rb
Following changes are introduced:
1. Select type of work changes into Apply to become section
2. This new section since it's the last and has a special style
for its delimiter, we are moving the dynamic sections' delimiters
on top of each section rather than after, so that the last dynamic
section's delimiter does not collide with the custom one that belongs
to Apply to become section.
3. Since concat/+ in ruby escape strings, we need to call an html_safe
on the our dynamic sections' bodies when prepending the delimiter.
https://dfedigital.atlassian.net/browse/GET-888
> Update Job Profile page markup

- app/views/user_personal_data/index.html.erb
- DOB should be a h2 rather than a h3 - DAC advise that we should not skip from h1 to h3
- Add sentence as per prototype to say “Your age and gender won’t affect the job suggestions we give you.”
https://dfedigital.atlassian.net/browse/GET-882
> Add copy change User Personal Information

- app/helpers/question_helper.rb
- app/views/questions/it_training.html.erb
- app/views/questions/job_hunting.html.erb
- app/views/questions/training.html.erb
- spec/features/questions_spec.rb
- spec/helpers/question_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-897
If user goes back mid journey, we should show progress indicator, until user gets
to action plan page.
Remaining behaviour remains the same.
Testing:
1) Normal journey shows normal progress
2) Interrupted journey shows only page where journey abandoned and progress
3) Going back shows progress mid journey
4) Action plan editing question shows no progress
> GET-897 Fix progression on question pages bug

- app/views/errors/course_postcode_search_error.html.erb
- app/views/errors/jobs_near_me_error.html.erb
- app/views/errors/postcode_search_error.html.erb
- app/views/errors/save_results_error.html.erb
- app/views/pages/location_ineligible.html.erb
- app/views/shared/_cookies_banner.html.erb
- app/views/skills/_job_profiles_with_skills.html.erb
- app/views/users/registration_email_sent_again.html.erb
- app/views/users/registration_results_saved.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-854
Add role button to all buttons which affect a user's journey. As per recommendation from DAC report:
If continuing through the service it is recommended that ‘Continue’ buttons are used for consistency purposes and to inform the user that they’ll be continuing throughout the service.
The ‘button’ is still a link in semantics, and has not been given a role of button as an alternative
page 41
✅ Axe tests pass
✅ Siteimprove does not fail on those new added roles
> GET-854 Add role button to links styled as buttons which affect journey

- app/models/skills_matcher.rb
- spec/models/skills_matcher_spec.rb
New order is as follows:
- number of skills matched;
- within that, order by job growth type
- within that, order by rarity of skills
Growth type codes:
- No data available: 0
- Falling: 1
- Stable: 2
- Growing: 3
- Growing strongly: 4
Introducing this new metric does not increase the
computation cost massively:
Before: 597.38ms
After: 618.77ms
https://dfedigital.atlassian.net/browse/GET-911
> Introduce growth_type in skills matcher query

- app/views/pages/_advice_on_finding_work.html.erb
- app/views/pages/_job_hunting.html.erb
- app/views/pages/cover_letter_advice.html.erb
- app/views/pages/cv_advice.html.erb
- app/views/pages/interview_advice.html.erb
- app/webpacker/styles/_back-to-top.scss
- app/webpacker/styles/application.scss
- config/locales/en.yml
- config/routes.rb
- spec/features/action_plan_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-817
* Add job hunting pages from action plan
* Add css for back to top button, taken from: https://github.com/alphagov/govuk-design-system/blob/e533f10315decff479f0f74a973aa525b3bf19e3/src/stylesheets/components/_back-to-top.scss as it's not in gov frontend
see https://design-system.service.gov.uk/components/back-link/ (at bottom of page)
> GET-817 add job hunting pages

- app/helpers/form_helper.rb
- app/views/check_your_skills/index.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/courses/index.html.erb
- app/views/job_profiles/index.html.erb
- app/views/job_profiles/results.html.erb
- app/views/job_profiles/skills/index.html.erb
- app/views/job_vacancies/index.html.erb
- app/views/user_personal_data/index.html.erb
- app/views/users/new.html.erb
- app/views/users/return_to_saved_results.html.erb
- spec/features/check_your_skills_spec.rb
- spec/features/find_training_courses_spec.rb
- spec/features/jobs_near_me_spec.rb
- spec/features/skills_builder_spec.rb
- spec/features/skills_matcher_spec.rb
- spec/features/user_registration_spec.rb
- spec/features/user_sign_in_spec.rb
- spec/features/your_information_spec.rb
- spec/helpers/form_helper_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-791
* Add method to accept object and return an error summary listing all errors from the object
* taken from: https://github.com/DFE-Digital/govuk_design_system_formbuilder/blob/88101aec9760233f0734de69a78e4db71112733e/lib/govuk_design_system_formbuilder/elements/error_summary.rb
* Formatting adheres to https://design-system.service.gov.uk/components/error-summary/
* Errors link to where they are on form on the page. We are building the error id the same way we build it within the form
* Add helper to pages:
user personal data:
check your skills search and results:
skill builder:
job profile search and results:
courses:
job vacancy search:
save and return to saved results:
> GET-791 Add error summary to all forms with validation

- app/views/shared/_save_or_return_to_your_results.html.erb
- spec/features/user_authentication_sidebar_spec.rb
- spec/features/user_registration_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-971
* User unlocks save your results after filling in PID form
* Fix all tests for return to save results/save your results
> GET-971 User unlocks save to results on PID form instead of selecting skills

- app/views/pages/_job_hunting.html.erb
- app/views/pages/_training.html.erb
- app/webpacker/styles/_action-plan.scss
Moving the spacing on top of the training and job
hunting options removes the weird spacing happening
when only one option is selected for each section.
https://dfedigital.atlassian.net/browse/GET-778
> Remove bottom spacing for buttons on action plan

- app/views/user_personal_data/_form.html.erb
Siteimprove captured the WAI-ARIA group name issue
around the PID form for the date of birth & gender sections.
https://dfedigital.atlassian.net/browse/GET-851
> Fix WAI-ARIA group name accessibility issue

- config/initializers/filter_parameter_logging.rb
Active admin uses its own parameters convention for
the date of birth: dob(3i), dob(2i), dob(1i).
Apparently there is a known issue with filtering date types
at the active admin page classes.
Adding dob among the filtered params at Rails level does fix
the problem.
https://dfedigital.atlassian.net/browse/GET-970
1. Configure Raven for local environment
2. Break the code intentionally by adding the following:
```ruby
controller do
def update
super
something.weird
end
end
```
to `user-personal_data/admin`
This will cause an exception that will be reported in Sentry. Check the Rails logs as well and you should see the dob params filtered out on both Rails & Sentry logs.
> Filter out dob params from ActiveAdmin form

- app/views/shared/_cookies_banner.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-962
Add aria label to cookie banner marked as role region to remove siteimprove
error. The label was taken from https://www.gov.uk/
> GET-962 Add aria label to cookie banner

- app/views/shared/feedback/_survey.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-943
Label should have same name as text area id, this removes all the errors
regarding the label and text area in siteimprove
> GET-943 Align label and text area name

- app/views/skills/index.html.erb
Fix the following issue:
https://www.w3.org/TR/WCAG20-TECHS/ARIA19
It was picked up as a warning by SiteImprove.
https://dfedigital.atlassian.net/browse/GET-942
> Fix accessibility issue

- app/views/pages/cookies_policy.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-964
Wrap whole text in link, so we don't get same different links same text
error from siteimrpove on page
> GET-964 Change link text to avoid siteimrpove link purpose error

- app/controllers/job_profiles_controller.rb
- spec/features/job_profile_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-989
disable vacancies temporarily until we investigate searching further. The page will just not render anything in that section for now
> GET-989 Temporarily disable job vacancies on job profile page

- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/pages/information_sources.html.erb
- app/webpacker/styles/_footer.scss
- app/webpacker/styles/application.scss
- config/locales/en.yml
- config/routes.rb
- spec/features/home_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-753
* Add new page and add path to routes
* Add back button which utilises the same logic as the continue
from the user save your results. This makes sure that you return to the
previous page if it exists, return to root if you didn't come from a previous
page, and return to root if you came from a page outside the app
* Override text underlining for footer lists as list should be underlined
> GET-753 Add new information sources page

- app/webpacker/styles/_footer.scss
On focus remove underline from list footer links to adhere to other links
in footer.
> Hotfix footer links

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- config/locales/en.yml
- spec/features/user_registration_spec.rb
- spec/features/user_sign_in_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-956
* Track if user saves their progress
* Track if user returns to their saved progress
* Track if existing user saves their progress
* Do not track non existing user trying to save their progress
* Do not track if user enters invalid email
* Change track event method parameters to accept a scope. We
need to do this to allow the same key to be mapped to different
values for the save and return.
GA key on heroku for testing
> GET-956 Track save and return events

- app/views/check_your_skills/_search_form.html.erb
- app/views/check_your_skills/results.html.erb
- app/views/job_profiles/_no_results.html.erb
- app/views/job_profiles/_search_form.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/search/_no_results.html.erb
- app/views/skills/_job_profiles_with_skills.html.erb
- config/locales/en.yml
- spec/features/check_your_skills_spec.rb
- spec/features/skills_builder_spec.rb
Targetted pages:
- Current job skills search
- Previous job skills search
- Previous job skills search has changes to h1
and is now consistent in prototype - wasn’t mentioned in description above
- Breadcrumbs can remain the same as they are for now as this can be addressed in Sophie’s ticket
https://dfedigital.atlassian.net/browse/GET-913
> Error message (no results found) are consistent

- app/controllers/passwordless/sessions_controller.rb
- app/controllers/users_controller.rb
- config/locales/en.yml
- spec/features/user_registration_spec.rb
- spec/features/user_sign_in_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-956
* Change label to have button for existing event
* Add event on clicking email link on sign in
> GET-956 Add tracking event for email link click on sign in 

- Dockerfile
- azure-pipelines.yml
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1025
https://github.com/sass/sassc-ruby/issues/146#issuecomment-542288556
https://northsail.io/articles/ruby-sassc-illegal-instruction
This seems to be happening sporadically now, disable this in bundle
in docker and azure pipeline
> GET-1025 Prevent segfault from sassc gem

- Gemfile
- Gemfile.lock
- azure-pipelines.yml
* The pipeline cache wasn't being renewed as the key was the gemfile lock.
Bust the cache so now it reads the bundle config
* Use new cache task and remove workaround as its no longer needed
> Bust pipeline cache, use new cache task

- app/views/job_profiles/_no_results.html.erb
- app/views/job_profiles/_search_form.html.erb
- app/views/job_profiles/index.html.erb
- app/views/job_profiles/results.html.erb
- app/views/skills_matcher/_sort_form.html.erb
- app/views/skills_matcher/index.html.erb
- app/webpacker/styles/_course.scss
- config/locales/en.yml
- spec/features/skills_matcher_spec.rb
Add tabs to skills matcher page
Also, add tabs to job profiles search page. The way
the original GDS component works needs a bit of tweaking
as follows:
The inactive tab has the link to the destination page and
not an anchor link as the component would expect. To achieve
that the inactive tab must not have the govuk-tabs__tab class,
otherwise, it will error as it's expecting something like:
'#element-id' which would not work well in our case.
https://dfedigital.atlassian.net/browse/GET-927
> Get 927 tabbed panel

- app.json
- app/services/spell_check_service.rb
- azure/config/dev1.parameters.json
- azure/config/dev2.parameters.json
- azure/config/prod.parameters.json
- azure/config/qa.parameters.json
- azure/config/uat.parameters.json
- azure/config/ut.parameters.json
- azure/template.json
- config/application.rb
- spec/features/check_your_skills_spec.rb
- spec/services/spell_check_service_spec.rb
Re-enable Bing Spell Check service.
Also add a new key for bing spell check api endpoint,
as with cognitive services enabled on all our
subscriptions the API also changes per subscription.
https://dfedigital.atlassian.net/browse/GET-523
> Get 523 enable bing

- app/services/find_a_course_service.rb
- spec/services/find_a_course_service_spec.rb
Also, handle different error codes returned from
the NCS service.
https://dfedigital.atlassian.net/browse/GET-1058
> Implement CourseDetails API endpoint

- app/services/find_a_course_service.rb
- spec/fixtures/files/find_a_course_search_response.json
- spec/services/find_a_course_service_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1057
* Find a course search accepts options and returns json response
* Options can be empty for some fields
* catch errors if there is an error from the API or from teh request
> GET-1057 Add search endpoint for find a course service

- app/views/courses/show.html.erb
Turns out the unformatted date was shown on the UI.
> Render the formatted start date on the UI

- azure-pipelines.yml
Our pipeline has recently started experiencing:
directory_maker.rb:18:in `mkdir':
Permission denied @ dir_s_mkdir - /build (Errno::EACCES)
To mitigate that temporarily we are granting permissions
to that directory.
> Temporary fix permissions issues

- app/controllers/user_personal_data_controller.rb
- spec/features/your_information_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1062
Do not check location eligibility when under API courses flag,
as we now support all regions. Maintain all other behaviour regarding
saving postcode to session, and tracking postcode.
> GET-1062 On API courses, do not check location eligibility on postcode

- app/controllers/courses_controller.rb
- app/models/user_session.rb
- spec/features/find_courses_near_me_spec.rb
- spec/models/user_session_spec.rb
Persist distance filter on the session
Add course_id and course_run_id among permitted
params.
Ensure the distance key is restored on the session when using the save and return journey.
https://dfedigital.atlassian.net/browse/GET-1046
> Persist distance filter on the session

- app/controllers/courses_controller.rb
- app/views/errors/courses_near_me_error.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/find_courses_near_me_spec.rb
- spec/routing/courses_spec.rb
If the NCS API is down we want to make sure users are
still able to use the service and get a relevant error
message when trying to find a relevant course.
https://dfedigital.atlassian.net/browse/GET-1061
> Add the courses near me error page for search

- app.json
The keys have now been added to the main review app settings, so we can officially start requiring them again
> Add back find a course keys to heroku app.json

- spec/features/find_courses_near_me_spec.rb
- yarn.lock
Using `yarn upgrade` update dependencies and include the minimist upgrade because of the CVE highlighted on versions less than 1.2
> Update conservatively minimist dependency

- app/decorators/course_details_decorator.rb
- app/views/courses/show.html.erb
- spec/decorators/course_details_decorator_spec.rb
- spec/features/find_courses_near_me_spec.rb
It looks like we were not using the decorated course description when rendering.
https://dfedigital.atlassian.net/browse/GET-1078
> Render the decorated course description

- app/views/courses/show.html.erb
- app/webpacker/styles/_course.scss
We noticed that for cases where a course description
has a very long url present it doesn't wrap properly,
so we need to force it.
https://dfedigital.atlassian.net/browse/GET-1079
> Forcing word wrapping on courses description

- app/decorators/job_profile_decorator.rb
- spec/decorators/job_profile_decorator_spec.rb
The original regex expression we were using to
identify all a tags and remove them was not capturing
all edge cases.
Rails has a method strip_links that does exactly this
so we are using it instead.
https://dfedigital.atlassian.net/browse/GET-1055
> Use strip_links for job profiles section

- app/decorators/course_details_decorator.rb
- app/views/courses/show.html.erb
- spec/decorators/course_details_decorator_spec.rb
Following formatting rules are introduced:
1. Add a 0 to prices like "£362.0"
2. Map QualificationLevel
```ruby
E = Entry Level
X = Unknown
1 - Level 1
2 - Level 2
...
```
3. Map CourseHours
```ruby
PartTime = Part-time
FullTime = Full-time
Flexible = Flexible
```
4. Map CourseType
```ruby
ClassroomBased = Classroom based
WorkBased = Work based
Online = Online
```
5. Don’t show CourseHours row if CourseHours = undefined
https://dfedigital.atlassian.net/browse/GET-1084
> Courses details formatting

- app/decorators/job_profile_decorator.rb
- app/views/courses/_search_filter.html.erb
- app/views/job_profiles/_apply_to_become.html.erb
- app/views/job_profiles/_apprenticeship.html.erb
- app/views/job_profiles/_dynamic_section.html.erb
- app/views/job_profiles/_highlights.html.erb
- app/views/job_profiles/_relevant_sections.html.erb
- app/views/job_profiles/_skills_section.html.erb
- app/views/pages/_advice_on_finding_work.html.erb
- app/views/pages/cover_letter_advice.html.erb
- app/views/pages/cv_advice.html.erb
- app/views/pages/interview_advice.html.erb
- app/webpacker/packs/courses-accordion.js
- app/webpacker/styles/_course.scss
- app/webpacker/styles/_job-profile.scss
- spec/decorators/job_profile_decorator_spec.rb
- Add all dynamic sections under accordion components
- Add the static sections under accordion components
- Make sure the first accordion component is not expanded
on big screens, unless user is on the courses page
- Add GDS accordion component to CV Advice page
- Add GDS accordion component to Cover letter page
- Add GDS accordion component to Interview page
> Add the accordion component for job profiles page

- app/views/pages/_find_other_courses.html.erb
- app/views/pages/_training.html.erb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1054
Move button to partial as with/without training options
we have different text under the button. Remove old link text and button
when no training is selected.
> GET-1054 Replace find a course link with button

- app/controllers/cookies_controller.rb
- app/helpers/application_helper.rb
- app/models/user_session.rb
- app/services/tracking_service.rb
- app/views/layouts/application.html.erb
- app/views/pages/cookies_policy.html.erb
- app/views/shared/_cookies_banner.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/tracking/_google_analytics.html.erb
- app/webpacker/packs/cookies-banner.js
- app/webpacker/styles/_cookies.scss
- config/routes.rb
- spec/features/cookies_banner_spec.rb
- spec/features/google_analytics_tracking_spec.rb
- spec/features/home_spec.rb
- spec/features/skills_matcher_spec.rb
- spec/features/user_feedback_survey_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/models/user_session_spec.rb
- spec/services/tracking_service_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-974
* update policy page as we no longer use azure app insights and to
reflect new cookie policy guidelines
* User's selected values for cookies should be saved to a session. We
are using boolean now to show a user accepted all cookies or partial
cookies
*  show/hide cookie banner as a session available on for user and avoid creating session on home page
* Amend cookies modal to not rely on js and appear in different forms
with and without js. With js we see two options, without only one option.
* Hide/show content according to js being enabled or disabled
* When js is disabled we are ok for now not to trap focus
* When a user accepts all cookies user session set to true, when
partial set to false
> GET- 974 Add new cookie banner

- config/locales/en.yml
Fix: Use Your job matches instead on the breadcrumbs.
> Use Your job matches instead.

- Dockerfile
We were not using a specific version in the Dockerfile,
to force ourselves to upgrade. Switch to specific version
now as we won't be maintaining the project anymore
> Lock Ruby alpine image version in Dockerfile

- Dockerfile
I missed updating the second part of the Dockerfile image to 2.6.5, hopefully this should resolve things.
> Update missing second step of image to 2.6.5

- yarn.lock
Upgrade kind-of to version 6.0.3 because of CVE
https://github.com/advisories/GHSA-6c8f-qphg-qjgp
> Update yarn depedency because of security alert

- app/controllers/courses_controller.rb
- app/models/course_search.rb
- app/services/find_a_course_service.rb
- spec/features/find_courses_near_me_spec.rb
- spec/models/course_search_spec.rb
- spec/services/find_a_course_service_spec.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1091
* Add response body to error message
* Raise postcode not found error when error body from API contains
the relevant message
* Catch the error message at the course search level and add
the validation error postcode not found to the object. We have
to check for errors then validation as `valid?` will overwrite
the existing errors and remove them.
* Add authenticity token to params to avoid errors
> GET-1091 Show validation error on postcode API error

- app/models/admin_user.rb
- spec/features/admin/authentication_spec.rb
- spec/models/admin_user_spec.rb
We recently noticed that resources in Azure Active Directory
can have the name attribute changed breaking our current
implementation which relied on the combination of
resource_id + email + name as the unique identifier
of authorised users for the Admin feature.
Relying instead on just resource_id + email as the unique
identifier will fix this issue.
https://dfedigital.atlassian.net/browse/GET-1095
Need to manually update the name of your user in the database and then try to login via AAD.
> Authentication process to ignore the resource name

- app/views/users/registration_results_saved.html.erb
- app/views/users/sign_in_link_sent.html.erb
Heading levels should only increase by one.
https://dequeuniversity.com/rules/axe/3.3/heading-order?application=axeAPI
https://dfedigital.atlassian.net/browse/GET-1071
> Ensure order of headings is semantically correct

- Dockerfile
jira-ticket: https://dfedigital.atlassian.net/browse/GET-1113
To avoid pulling in any new versions, lock the nodejs version in the dockerfile
deployed to dev1 for testing
> GET-1113 Lock nodejs version in dockerfile

- app/services/health_check/notify_check.rb
jira-ticket: https://dfedigital.atlassian.net/browse/GET-787
When displaying the health check page, we should show a failure
of a particular service rather than the whole page crashing. Make
sure that we catch *all* notify service errors so it doesn't fail
on NET::Http errors such as SocketError
> GET-787 Rescue all errors from notify service in healthcheck

- app/middleware/status_report.rb
- spec/requests/health_check_spec.rb
Currently, our health check endpoint will return a 207 code
when at least one of our 3rd party services responds with :warn.
Azure will deem the overall system as unhealthy switching to
maintenance page.
We do want our users to still be able to access our
service. To mitigate this, our health endpoint needs to
return 200 instead of 207 even when at least one of our 3rd
party services might respond with a :warn code.
More on how health probes work in Azure:
https://docs.microsoft.com/en-us/azure/frontdoor/front-door-health-probes#health-probe-responses
https://dfedigital.atlassian.net/browse/GET-1144
> Health endpoint responds with 200 for :warn, :pass

- azure/config/prod.parameters.json
- azure/config/uat.parameters.json
Because of the COV19 issue and with everyone working
outside the office, restriction of access by IP did not
seem like a sustainable solution anymore with
IPs being dynamic.
We've decided to temporarily allow access to any IP.
This is not compromising security at all,
as the Admin remains an authentication and permission
based access section of our service.
We've kept the old office IP ranges, as when things will
go to normal, we can always revert back to IP restriction
easily. Should this become a permanent solution, the IP
ranges can be removed completely.
> Disable IP restriction for Admin temporarily

- azure/config/prod.parameters.json
- azure/config/uat.parameters.json
Initially we tried adding 0.0.0.0/0 as an additional
entry to the existing configuration. This means that
any IP is allowed access. However, there seems to still
be an access issue for people with the DfE KIT on.
Because we don't have the DfE KIT on it's hard to debug
what the issue is. To unblock things, we decided to remove
the IP Restriction config completely.
https://dfedigital.atlassian.net/browse/GET-1147
> Remove the IP Restriction config

- app/controllers/job_vacancies_controller.rb
- app/views/job_vacancies/_search_filter.html.erb
- app/views/job_vacancies/index.html.erb
- app/webpacker/packs/application.js
- app/webpacker/packs/jobs-near-me-accordion.js
- app/webpacker/styles/_jobs-near-me.scss
- app/webpacker/styles/application.scss
- spec/features/jobs_near_me_spec.rb
Add distance filter to Jobs Near Me page:
Add accordion to allow the user to filter by distance
By default, 20 miles distance
- Persist distance filter if navigate away from page
- Collapse in mobile by default
- Expand on desktop or tablet
- Error messages to stay the same - filter should expand and red and summary shown at top (like with courses)
If there are no results, add a new bullet point (second)
Content: “using the filters to search a wider local area”
https://dfedigital.atlassian.net/browse/GET-1110
> Add distance filter to Jobs Near Me page

- app/views/job_vacancies/index.html.erb
Simplify copy on the job vacanices page when
no results are returned.
> Update copy for no job vacancies page

- app/models/user_personal_data.rb
- config/locales/en.yml
- spec/factories/user_personal_data.rb
- spec/features/your_information_spec.rb
Adding more granular date of birth validation for
the PID form for the following cases:
- If no date is entered
- If an incomplete date is entered - missing day
- If an incomplete date is entered - missing month
- If an incomplete date is entered - missing year
- If an incomplete date is entered - missing day and month
- If an incomplete date is entered - missing day and year
- If an incomplete date is entered - missing month and year
- If the date entered is not a real one/not number characters
- If the date is in the future when it needs to be in the past
- If the date of birth is earlier than 1900
https://dfedigital.atlassian.net/browse/GET-716
> Refactor date of birth validation on PID form

- app/controllers/courses_controller.rb
- spec/features/find_courses_near_me_spec.rb
Because of GDPR concerns about reporting the
full postcode people search on the courses page
we decided to report just the outcode to
Google Analytics.
https://dfedigital.atlassian.net/browse/GET-1151
> Track the outcode on courses page

- app/services/find_a_job_service.rb
- spec/services/find_a_job_service_spec.rb
After some data analysis we discovered that we
can get more relevant results if we use:
- qtl as query string param for job titles that have
only one word
- qph as query string param for job titles that have
multiple words
> Improve querying for job vacancies

- app/controllers/questions_controller.rb
- app/views/pages/_job_hunting.html.erb
- app/views/questions/edit_job_hunting.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/action_plan_spec.rb
Add standalone edit page for Job Hunting options
Track selected options in GA.
https://dfedigital.atlassian.net/browse/GET-1033
> Add standalone edit page for Job Hunting options

- app/views/skills_matcher/index.html.erb
Job matches page will only display the pagination
separator if users get more than one page of results.
https://dfedigital.atlassian.net/browse/GET-1121
> Add pagination separator for 1+ pages

- app/views/pages/training/_with_options.html.erb
- spec/features/questions_spec.rb
Users should be able to deeplink to action plan
even if they've only answered just the first
training question.
The service should not break when this happens.
https://dfedigital.atlassian.net/browse/GET-1109
> Bugfix: Deeplinking to action plan

- spec/support/personal_data.rb
Running the specs in offline mode, seem to throw
in some cases the following error:
Webdrivers::ConnectionError:
Can not reach https://chromedriver.storage.googleapis.com/
This is coming from spec/support/personal_data when trying
to deep-link straight into the PID form and it looks
like an interaction issue with Webdriver.
Getting to PID from the landing page seems to solve the issue,
as the cookies modal is accepted at that level now.
Also, removes the need to identify the specs that have the :js
tag.
> Hotfix: Overcome webdriver connection issue

- app/views/job_profiles/_job_profile.html.erb
- app/views/job_profiles/show.html.erb
- spec/features/job_profile_spec.rb
- spec/features/skills_matcher_spec.rb
Persist search term when returning to job matches
If users look for other job profiles on the job
matches page, then select one result and decide
to navigate back to job matches through the
breadcrumbs, the search term will now be persisted.
https://dfedigital.atlassian.net/browse/GET-779
> Get 779 breadcrumbs fix

- app/controllers/job_profiles_skills_controller.rb
- spec/features/skills_builder_spec.rb
Currently, if users are trying to access a job profile
that doesn't exist, they get a 500 page because of the
type of exception that is raised.
Raising a RecordNotFound instead will fix this issue.
https://dfedigital.atlassian.net/browse/GET-919
> Display a 404 page when a resource doesn't exist

- app/controllers/job_profiles_controller.rb
- spec/features/job_profile_spec.rb
When trying to access a job profile that one wants
to target, and the profile id does not exist, users
should see a 404 page.
> Display a 404 page on a missed route

- app/middleware/status_report.rb
Frontdoor has a security check routine that is ran
every couple of hours. Among other checks, it tries
to call a DEBUG method against our server.
As a good security practice the server should respond
with method not allowed in this case. This will also
turn off the noise in Sentry.
> Do not allow methods outside accepted HTTP methods

- app/decorators/job_vacancy_decorator.rb
- app/views/job_vacancies/_job_vacancy.html.erb
- spec/decorators/job_vacancy_decorator_spec.rb
The 'bold' tag is used to highlight text.
Solution: Use the 'strong' tag instead.
https://dfedigital.atlassian.net/browse/GET-966
> Accessibility fix: 1.3.1 Info and Relationships

- app/views/job_profiles/skills/index.html.erb
Solution:
Remove the `<p>` and `<span>` containing the hint text from the legend.
Associate each checkbox with the hint text by using aria-described by.
https://dfedigital.atlassian.net/browse/GET-951
> Restructure the markup in accordance with DAC

- app/views/job_profiles/index.html.erb
- app/views/shared/search/_form.html.erb
- app/views/shared/search/_results_form.html.erb
DAC Report:
Non-descriptive labelling
Labels were encountered that were not descriptive.
Solution:
Remove the word button from the label as this element
is a button, it will read as such to a screen reader user.
https://dfedigital.atlassian.net/browse/GET-950
> Search labels should not contain the word button

- app/views/job_profiles/_highlights.html.erb
1. According to DAC, the information provided via the aria-label
for images on the job profiles page does not provide
any more useful information. This may be confusing for some
screen reader users in a non-testing environment.
2. Also, the visual separators should not be announced
to screen reader users.
Solution:
1. Remove the role of image and the aria-label from all four <div>
elements as screen reader users do not need to
be aware of this information.
2. Use aria-hidden="true" on separators.
https://dfedigital.atlassian.net/browse/GET-952
> Remove aria-label from the img tags

- app/models/job_vacancy_search.rb
- spec/features/jobs_near_me_spec.rb
If the user accidentally adds unwanted characters to
the page number the service should not break.
https://dfedigital.atlassian.net/browse/GET-780
> Altering page number does not break the service

- config/initializers/content_security_policy.rb
Introducing the Content Security Policy (CSP) seems to
reject the gtag inline JS script on UAT env as it has a
different SHA.
> UAT & PRD env require different SHAs for gtag inline JS

- config/initializers/content_security_policy.rb
We currently run FB campaigns and Sentry reported that the
following uri: https://connect.facebook.net was blocked.
We need to whitelist it.
> CSP needs to allow the FB uri

- config/initializers/content_security_policy.rb
We've recently seen in Sentry that our CSP rejected
https://www.google-analytics.com/analytics.js script.
White-listing it.
> Allow analytics.js to be executed

- yarn.lock
CVE-2020-8116
high severity
Vulnerable versions: < 5.1.1
Patched version: 5.1.1
Prototype pollution vulnerability in dot-prop npm package version 5.1.0
and earlier allows an attacker to add arbitrary properties to
JavaScript language constructs such as objects.
However, it is a sub-dependency of @rails/webpacker. Upgrading
webpacker version to 5.1.1 will upgrade dot-prop to the right
version.
> Upgrade dot-prop 4.1.1 -> 5.2.0

- package.json
- yarn.lock
Version 2.1.2 has been detected with the following
vulnerability:
CVE-2020-7660
high severity
Vulnerable versions: < 3.1.0
Patched version: 3.1.0
serialize-javascript prior to 3.1.0 allows remote attackers to
inject arbitrary code via the function "deleteFunctions"
within "index.js".
> Bump serialize-javascript 2.1.2 -> 3.1.0

- package.json
- yarn.lock
node-forge versions < 0.10.0 have been identified
with the following vulnerability:
https://github.com/advisories/GHSA-92xj-mqp7-vmcj
> Upgrade node-forge 0.9.0 -> 0.10.0
